### ISSUE TITLE
MediaSourceType wrong validation

### ISSUE THREAD

**Issue by TonyTangAndroid** [brianwernick/ExoMedia#143]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 0.  Using an url (for example, [http://tracking.feedpress.it/link/4776/2831033/Essentialism_-_Do_Less_and_Achieve_More_Podcast_142.mp3](http://tracking.feedpress.it/link/4776/2831033/Essentialism_-_Do_Less_and_Achieve_More_Podcast_142.mp3) ) that contains keyword like "m3u8", "mpd", "ism", which is referenced as a MediaSourceType type in 

`  HLS(".*m3u8.*"),
    DASH(".*mpd.*"),
    SMOOTH_STREAM(".*ism.*"),
    DEFAULT(null);`

will stably reproduce the following exception.

I have committed the code to reproduce this by adding the Exception parameter in the callback.
Please refer to this link for more details.

https://github.com/brianwernick/ExoMedia/compare/3.0...OttoRadio:3.0

###### Expected Result
Url with "ism" should be able to play normal as other url resources.
###### Actual Result
``BaseMediaApi: Response code: 404
                                                                                    com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
                                                                                        at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:97)
                                                                                        at com.google.android.exoplayer.upstream.DataSourceInputStream.open(DataSourceInputStream.java:56)
                                                                                        at com.google.android.exoplayer.upstream.UriLoadable.load(UriLoadable.java:92)
                                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)``

**Comment by TonyTangAndroid** [comment]
I believe the root cause is that the Exoplayer will treat this kind of resource as SMOOTH_STREAM resource instead of ordinary resource and caused the issue.

**Comment by brianwernick** [comment]
Yeah, its due to the "ism" part of "Essentialism" which is being captured by `.*ism.*`.  I've been worried about the way we are performing the HLS, Smooth Stream, and Dash determinations but have yet to come up with a more dependable solution.  If you have any ideas they would be greatly welcomed

**Comment by TonyTangAndroid** [comment]
I have checked the url pattern of HLS(".*m3u8.*"), DASH(".*mpd.*"), SMOOTH_STREAM(".*ism.*"), it seems that there is no fixed pattern in the uri. For now, I have a temporary fix for my own application which only uses mp3 in the follow way:

1, remove all url query parameters.
2, check the url end withs ".mp3".

If it is, it will return the default type directly. 

But again, this is a hacker way to temporarily fix this issue.  

https://github.com/brianwernick/ExoMedia/compare/3.0...OttoRadio:3.0

**Comment by se-bastiaan** [comment]
I've seen this also in url's like `http://livestreams.omroep.nl/live/npo/tvlive/ned1/ned1.isml/ned1.m3u8`. Worked around it of course, but it can cause issues.

**Comment by brianwernick** [comment]
So after thinking about this for a while this is what I have come up with, proceeding with each subsequent step if the previous one fails.

1. Parse the URL specified for simple cases such as "file://" or "http://someurl/mp4" or "http://someurl.mp4" (where the last 2 just look at the last segments)
2. Send a HEAD request to the specified URL and look at the resulting `Content-Type`
3. Use the current broad comparison that uses very loose regex (e.g. `*m3u8*`)

Does this seem like a decent set of steps for media format determination?

**Comment by TonyTangAndroid** [comment]
I do not know a better way to address this issue in my limited knowledge.  It sounds good to go. For my personal project, it only plays mp3 files, so I kind of hacked it by checking the end part of the url without parameters.

**Comment by se-bastiaan** [comment]
MimeTypes.java does not contain the mimetype of a smooth streaming manifest from the samples: 'application/vnd.ms-sstr+xml'. And the M3U8 `Content-Type` from the samples is `application/xml`, not `application/x-mpegURL`. Seems it can never be easy.

**Comment by brianwernick** [comment]
So i added a more accurate type check (essentially what I listed above but skipping step 2).  If you find any url formats that I missed (e.g. "test.ism/manifest", "test.mp3" are the two current formats) please let me know or create a PR with the update.
