### ISSUE TITLE
java.lang.RuntimeException: Unable to start service for Lock Screen Notification 

### ISSUE THREAD

**Issue by vsay01** [brianwernick/ExoMedia#156]
- [yes] I have verified there are no duplicate active or recent bugs, questions, or requests

Thank for great library.

###### Include the following:
 - ExoMedia version: have occurred since old version until `2.5.5` (currently I test this version)
 - Device OS version: 4 and 5
 - Devide Manufacturer: `Samsung`, LGE, Huawei
 - Device Name: `Unknown`
 
###### Reproduction Steps
 I used the crash report to capture crash so I don't know what are the steps that reproduce them.

###### Crash
I think the issue happens because of the bitmap recycling as mentioned here [http://stackoverflow.com/questions/13737485/java-lang-illegalstateexception-cant-parcel-a-recycled-bitmap-error-occurs](url).

The crash point to method updateLargeNotification in AudioService class and here is how I implement it:

```
@Override
    protected void updateLargeNotificationImage(int size, MediaItem playlistItem) {
        if (notificationImageTarget != null){
            if (playlistItem != null && !playlistItem.getThumbnailUrl().equals("")){
                picasso.load(playlistItem.getThumbnailUrl())
                        .placeholder(getResources().getDrawable(R.drawable.cover_album))
                        .error(getResources().getDrawable(R.drawable.cover_album))
                        .into(notificationImageTarget);     // This is where error pointed to
            }
            else{
                Picasso.with(getApplicationContext()).load(R.drawable.cover_album).into(notificationImageTarget);
            }
        }
    }
```
```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.example.testmedia.service.AudioService@42831b38 with Intent { act=remote_action_previous cmp=com.example.testmedia/.service.AudioService }: java.lang.IllegalStateException: Can't parcel a recycled bitmap
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2705)
       at android.app.ActivityThread.access$2100(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.IllegalStateException: Can't parcel a recycled bitmap
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:346)
       at android.graphics.Bitmap.writeToParcel(Bitmap.java:1483)
       at android.widget.RemoteViews$BitmapCache.writeBitmapsToParcel(RemoteViews.java:983)
       at android.widget.RemoteViews.writeToParcel(RemoteViews.java:2501)
       at android.app.Notification.writeToParcel(Notification.java:924)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:312)
       at android.app.NotificationManager.notify(NotificationManager.java:136)
       at android.app.NotificationManager.notify(NotificationManager.java:109)
       at com.devbrackets.android.exomedia.EMNotification.updateNotificationInformation(EMNotification.java:174)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.updateNotification(EMPlaylistService.java:1164)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.onLargeNotificationImageUpdated(EMPlaylistService.java:854)
       at com.example.testmedia.service.service.AudioService.access$300(AudioService.java:208)
       at com.example.testmedia.service.AudioService$NotificationTarget.onBitmapLoaded(AudioService.java:330)
       at com.squareup.picasso.RequestCreator.into(RequestCreator.java:518)
       at com.example.testmedia.service.AudioService.updateLargeNotificationImage(AudioService.java:285)
       at com.example.testmedia.service.AudioService.updateLargeNotificationImage(AudioService.java:208)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.mediaItemChanged(EMPlaylistService.java:1204)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.startItemPlayback(EMPlaylistService.java:899)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.performPrevious(EMPlaylistService.java:605)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.handleRemoteAction(EMPlaylistService.java:1239)
       at com.devbrackets.android.exomedia.service.EMPlaylistService.onStartCommand(EMPlaylistService.java:425)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2688)
       at android.app.ActivityThread.access$2100(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5001)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:736)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
Thank.

**Comment by brianwernick** [comment]
As a note: this may never get fixed in ExoMedia because the Playlist support has been extracted in to [PlaylistCore](https://github.com/brianwernick/PlaylistCore).  I would recommend starting the migration process soon (if you look at the 3.0 branch I'm using `PlaylistCore` in the demo)

**Comment by brianwernick** [comment]
I'm going to close this because I won't be releasing any more 2.x versions and the 3.0 version has removed playlist support
