### ISSUE TITLE
Cannot play mp3 that has meta data as thumbnail

### ISSUE THREAD

**Issue by vsay01** [brianwernick/ExoMedia#178]
- [ YES] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Moto`
 - Device Name: `G`
 
###### Reproduction Steps
Play song mp3 whose meta data has thumbnail

###### Expected Result
song play
###### Actual Result
Error as following:
```
ExoPlayerImplInternal: Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                     Caused by: com.google.android.exoplayer.extractor.ExtractorSampleSource$UnrecognizedInputFormatException: None of the available extractors (WebmExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, TsExtractor, FlvExtractor, PsExtractor) could read the stream.
                                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractorHolder.selectExtractor(ExtractorSampleSource.java:794)
                                                                                        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:725)
                                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)
```
Noted:
I removed the meta thumbnail from the mp3 file, and it can play well.

**Comment by brianwernick** [comment]
This looks like something that should be logged against the `ExoPlayer` as none of this points to `ExoMedia`

**Comment by vsay01** [comment]
Ok, I will ask this question in the exoMedia repo, Thank
There also another issue that it cannot play mp3 whose url start with http as well

**Comment by brianwernick** [comment]
OK, please be sure to link the ExoPlayer issue (either add the link as a comment here, or add this issue as a comment in the ExoPlayer bug)

**Comment by Kisty** [comment]
Just to let you know, this issue has been closed on the ExoPlayer project. You can close this. https://github.com/google/ExoPlayer/issues/1445

**Comment by brianwernick** [comment]
Thanks @Kisty
