### ISSUE TITLE
NullpointerException

### ISSUE THREAD

**Issue by maohieng** [brianwernick/ExoMedia#18]
While on the play audio screen, close notification, the player stops playing normally. If click play button on the play screen, error occur. 

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
            at android.content.ComponentName.<init>(ComponentName.java:78)
            at android.content.Intent.<init>(Intent.java:4160)
            at com.devbrackets.android.exomedia.EMNotification.createPendingIntent(EMNotification.java:299)
            at com.devbrackets.android.exomedia.EMNotification.getCustomNotification(EMNotification.java:213)
            at com.devbrackets.android.exomedia.EMNotification.getNotification(EMNotification.java:172)
            at com.devbrackets.android.exomedia.service.EMPlaylistService.setupForeground(EMPlaylistService.java:803)
            at com.devbrackets.android.exomedia.service.EMPlaylistService.performPlay(EMPlaylistService.java:758)
            at com.devbrackets.android.exomedia.service.EMPlaylistService.performPlayPause(EMPlaylistService.java:535)
            at com.devbrackets.android.exomedia.service.EMPlaylistService.handleRemoteAction(EMPlaylistService.java:1130)
            at com.devbrackets.android.exomedia.service.EMPlaylistService.onStartCommand(EMPlaylistService.java:374)

**Comment by brianwernick** [comment]
FIxed
