### ISSUE TITLE
Binary XML file: Error inflating class com.devbrackets.android.exomedia.EMVideoView

### ISSUE THREAD

**Issue by sureshvaavel** [brianwernick/ExoMedia#188]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 
Using the library with gradle 2.0.0 causes this issue

**Comment by brianwernick** [comment]
Please post your layout file.  I'm not able to reproduce this

**Comment by sureshvaavel** [comment]
<LinearLayout android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingLeft="10dp"
    android:paddingRight="10dp"
    android:paddingTop="15dp"
    android:layout_marginLeft="5dp"
    android:layout_marginTop="10dp"
    android:background="@drawable/chat_border"
    android:layout_marginRight="5dp"
    android:layout_marginBottom="5dp"
    android:orientation="vertical"
    xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android">

   <com.devbrackets.android.exomedia.ui.widget.EMVideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="175dp"
            android:visibility="gone"
            EMVideoView:defaultControlsEnabled="true"/>


    </RelativeLayout>

**Comment by martinothamar** [comment]
Experienced this as well. Nexus 3 Android 4.3. Exceptions caused by ClassNotFoundException when inflating the fragment. Also using Gradle 2.0.0.

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".Fragments.Onboarding.Slide2">

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/videoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        EMVideoView:defaultControlsEnabled="false"/>

    <ImageView
        android:layout_width="48dp"
        android:layout_height="48dp"
        android:id="@+id/onboardingNextButton"
        android:src="@drawable/ic_keyboard_arrow_right_white_48dp"
        android:layout_marginBottom="25dp"
        android:layout_marginRight="25dp"
        android:layout_gravity="bottom|right"
        android:adjustViewBounds="false"
        android:clickable="true"
        android:scaleType="fitXY"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true" />

</RelativeLayout>
```

**Comment by se-bastiaan** [comment]
I cannot reproduce this. It works perfectly fine in all my emulators and my physical devices.
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:baselineAligned="false"
    android:orientation="vertical"
    android:background="@android:color/black">

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:defaultControlsEnabled="false" />

    <ProgressBar
        android:id="@+id/progress_indicator"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true" />

</RelativeLayout>
```

**Comment by brianwernick** [comment]
@martinothamar Are you using the correct version package?  `com.devbrackets.android.exomedia.ui.widget.EMVideoView` package is only for the `3.0.0` version, `com.devbrackets.android.exomedia.EMVideoView` is for previous versions.

**Comment by martinothamar** [comment]
Thats probably it then! I'm using 2.5.6 stable. Thanks.

**Comment by sureshvaavel** [comment]
That might be the issue for me as well . Thanks @brianwernick  it works now @se-bastiaan

**Comment by slashrootv200** [comment]
Still able to reproduce this using both .aar file and as dependancy

used com.devbrackets.android.exomedia.ui.widget.EMVideoView

ExoMedia version: 3.0.0-preview2
Device OS version: 6.0
Devide Manufacturer: Motorola
Device Name: Moto G3

**Comment by ohenepee** [comment]
Having the same issue right now

ExoMedia Version: 3.0.5
OS Version: 4.1.2
Device Model: Motorola Droid Razr XT912

```
com.name.hello E/AndroidRuntime: FATAL EXCEPTION: main
								   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.name.hello/com.name.hello.MainActivity}: android.view.InflateException: Binary XML file line #44: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
									   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2136)
									   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174)
									   at android.app.ActivityThread.access$700(ActivityThread.java:141)
									   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267)
									   at android.os.Handler.dispatchMessage(Handler.java:99)
									   at android.os.Looper.loop(Looper.java:137)
									   at android.app.ActivityThread.main(ActivityThread.java:5059)
									   at java.lang.reflect.Method.invokeNative(Native Method)
									   at java.lang.reflect.Method.invoke(Method.java:511)
									   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
									   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
									   at dalvik.system.NativeStart.main(Native Method)
									Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
									   at android.view.LayoutInflater.createView(LayoutInflater.java:613)
									   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
									   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
									   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
									   at com.name.hello.MainActivity.onCreate(MainActivity.java:20)
									   at android.app.Activity.performCreate(Activity.java:5058)
									   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
									   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
									   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174) 
									   at android.app.ActivityThread.access$700(ActivityThread.java:141) 
									   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267) 
									   at android.os.Handler.dispatchMessage(Handler.java:99) 
									   at android.os.Looper.loop(Looper.java:137) 
									   at android.app.ActivityThread.main(ActivityThread.java:5059) 
									   at java.lang.reflect.Method.invokeNative(Native Method) 
									   at java.lang.reflect.Method.invoke(Method.java:511) 
									   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
									   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
									   at dalvik.system.NativeStart.main(Native Method) 
									Caused by: java.lang.reflect.InvocationTargetException
									   at java.lang.reflect.Constructor.constructNative(Native Method)
									   at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
									   at android.view.LayoutInflater.createView(LayoutInflater.java:587)
									   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
									   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
									   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
									   at com.name.hello.MainActivity.onCreate(MainActivity.java:20) 
									   at android.app.Activity.performCreate(Activity.java:5058) 
									   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
									   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100) 
									   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174) 
									   at android.app.ActivityThread.access$700(ActivityThread.java:141) 
									   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267) 
									   at android.os.Handler.dispatchMessage(Handler.java:99) 
									   at android.os.Looper.loop(Looper.java:137) 
									   at android.app.ActivityThread.main(ActivityThread.java:5059) 
									   at java.lang.reflect.Method.invokeNative(Native Method) 
									   at java.lang.reflect.Method.invoke(Method.java:511) 
									   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
									   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
									   at dalvik.system.NativeStart.main(Native Method) 
									Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.devbrackets.android.exomedia.core.video.ExoVideoView
									   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
									   at android.view.ViewStub.inflate(ViewStub.java:258)
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:688)
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:665)
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:627)
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:101)
									   at java.lang.reflect.Constructor.constructNative(Native Method) 
									   at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
									   at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
									   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
									   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
									   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
									   at com.name.hello.MainActivity.onCreate(MainActivity.java:20) 
									   at android.app.Activity.performCreate(Activity.java:5058) 
									   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
									   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100) 
									   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174) 
									   at android.app.ActivityThread.access$700(ActivityThread.java:141) 
									   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267) 
									   at android.os.Handler.dispatchMessage(Handler.java:99) 
									   at android.os.Looper.loop(Looper.java:137) 
									   at android.app.ActivityThread.main(ActivityThread.java:5059) 
									   at java.lang.reflect.Method.invokeNative(Native Method) 
									   at java.lang.reflect.Method.invoke(Method.java:511) 
									   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
									   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
									   at dalvik.system.NativeStart.main(Native Method) 
									Caused by: java.lang.ClassNotFoundException: Didn't find class "com.devbrackets.android.exomedia.core.video.ExoVideoView" on path: /data/app/com.name.hello-2.apk
									   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
									   at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
									   at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
									   at android.view.LayoutInflater.createView(LayoutInflater.java:552)
									   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:466) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
									   at android.view.ViewStub.inflate(ViewStub.java:258) 
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:688) 
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:665) 
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:627) 
									   at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:101) 
									   at java.lang.reflect.Constructor.constructNative(Native Method) 
									   at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
									   at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
									   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
									   at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
									   at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
									   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
									   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
									   at com.name.hello.MainActivity.onCreate(MainActivity.java:20) 
									   at android.app.Activity.performCreate(Activity.java:5058) 
									   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
									   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100) 
									   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2174) 
									   at android.app.ActivityThread.access$700(ActivityThread.java:141) 
									   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1267) 
									   at android.os.Handler.dispatchMessage(Handler.java:99) 
									   at android.os.Looper.loop(Looper.java:137) 
									   at android.app.ActivityThread.main(ActivityThread.java:5059) 
									   at java.lang.reflect.Method.invokeNative(Native Method) 
									   at java.lang.reflect.Method.invoke(Method.java:511) 
									   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
									   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555) 
									   at dalvik.system.NativeStart.main(Native Method) 
```

And this is my layout
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.peps.android.newhello.MainActivity">

    <LinearLayout
        android:id="@+id/lcontainer"
        android:layout_centerHorizontal="true"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <Button
            android:text="Begin"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/button1"
            android:textSize="20dp"
            android:onClick="startService" />

        <Button
            android:text="End"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/button2"
            android:textSize="20dp"
            android:onClick="stopService" />

    </LinearLayout>

    <LinearLayout
        android:layout_below="@+id/lcontainer"
        android:layout_marginTop="20dp"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.devbrackets.android.exomedia.ui.widget.EMVideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            EMVideoView:useDefaultControls="true" />

    </LinearLayout>

</RelativeLayout>
```

**Comment by alexWr** [comment]
I have the same issue as @ohenepee. I generate the aar file, add to my project and it generate inflate error

**Comment by brianwernick** [comment]
If you are having this issue post a *NEW* issue. This one was resolved and your issues probably isn't related
