### ISSUE TITLE
NPE in SurfaceTexture view

### ISSUE THREAD

**Issue by AngelJedi** [brianwernick/ExoMedia#192]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

05-03 09:00:43.128 7457-7457/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.lds.medialibrary.dev, PID: 7457
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.SurfaceTexture.setDefaultBufferSize(int, int)' on a null object reference
                                                     at com.devbrackets.android.exomedia.core.video.ResizingTextureView.updateVideoSize(ResizingTextureView.java:264)
                                                     at com.devbrackets.android.exomedia.core.video.ExoVideoView.onVideoSizeChanged(ExoVideoView.java:240)
                                                     at com.devbrackets.android.exomedia.ui.widget.EMVideoView$MuxNotifier.onVideoSizeChanged(EMVideoView.java:895)
                                                     at com.devbrackets.android.exomedia.ui.widget.EMVideoView$MuxNotifier.onVideoSizeChanged(EMVideoView.java:876)
                                                     at com.devbrackets.android.exomedia.core.EMListenerMux.onVideoSizeChanged(EMListenerMux.java:151)
                                                     at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.onVideoSizeChanged(EMExoPlayer.java:456)
                                                     at com.google.android.exoplayer.MediaCodecVideoTrackRenderer$1.run(MediaCodecVideoTrackRenderer.java:564)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by brianwernick** [comment]
This has actually already been fixed, and will be in the next release

**Comment by sooorajjj** [comment]
@brianwernick can you link which commit fixed this have saimilar issues with SurfaceTexture here https://github.com/googlecodelabs/tensorflow-for-poets-2/blob/master/android/src/org/tensorflow/demo/CameraConnectionFragment.java#L516

**Comment by brianwernick** [comment]
@sooorajjj https://github.com/brianwernick/ExoMedia/commit/fd332a5c1e67114e3cd592bedf05ba755eaffaa7

**Comment by sooorajjj** [comment]
@brianwernick Thanks
