### ISSUE TITLE
ResizingTextureView.clearSurface crash

### ISSUE THREAD

**Issue by gparigibini** [brianwernick/ExoMedia#224]
Hi Brian, 
I'm using the latest version of the library (preview3), but I'm getting a bug report from some users. Here's the stack trace:

```
Fatal Exception: java.lang.UnsupportedOperationException: eglCreateWindowSurface() can only be called with an instance of SurfaceView, SurfaceHolder or SurfaceTexture at the moment, this will be fixed later.
       at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:95)
       at com.devbrackets.android.exomedia.core.video.ResizingTextureView.clearSurface(ResizingTextureView.java:238)
       at com.devbrackets.android.exomedia.core.EMListenerMux.onStateChanged(EMListenerMux.java:136)
       at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.reportPlayerState(EMExoPlayer.java:661)
       at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.onPlayerStateChanged(EMExoPlayer.java:464)
       at com.google.android.exoplayer.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:207)
       at com.google.android.exoplayer.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4898)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

At the moment, I've received reports from gt_i9300 and eg970be, all using Android 4.1.2.

My quick fix for using this library into production would be to fork the library and capture the error inside the 'ResizingTextureView.clearSurface' method.

Do you have any better suggestion?

Btw, thank you very much for this great library :)

**Comment by brianwernick** [comment]
In the short term capturing the crash is the easiest and quickest thing however for the long run it will be worth while to limit the calls to only supported devices.  And as far as the forking goes, it depends on how quickly you want to get an update out to your users.  I'm hoping that I can get a beta or preview out by this weekend, so if that's not quick enough then forking is the way to go.

**Comment by brianwernick** [comment]
This should be fixed in the linked PR (I haven't seen this crash on my devices so I can't be completely sure)

**Comment by gparigibini** [comment]
Perfect, thank you so much for the quick response!
