### ISSUE TITLE
Surface is not released

### ISSUE THREAD

**Issue by ypresto** [brianwernick/ExoMedia#258]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Reproduction Steps
 0. Start playing video in fragment.
 0. finish() hosting activity.

###### Expected Result
No warning is shown.

###### Actual Result
StrictMode shows below warning:
```
06-27 00:39:22.735 4173-4183/com.kurashiru E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                         java.lang.Throwable: Explicit termination method 'release' not called
                                                             at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                             at android.view.Surface.setNativeObjectLocked(Surface.java:459)
                                                             at android.view.Surface.<init>(Surface.java:145)
                                                             at com.devbrackets.android.exomedia.core.video.ExoVideoView$EMExoVideoSurfaceTextureListener.onSurfaceTextureAvailable(ExoVideoView.java:276)
```

**Comment by brianwernick** [comment]
This has been fixed in https://github.com/brianwernick/ExoMedia/commit/d7c63bbfb7671ac2afb0ca64807e751ac1e8f371
