### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by mapm14** [brianwernick/ExoMedia#274]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Motorola`
 - Device Name: `XT1068`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Nexus 6`
 
###### Reproduction Steps
 1. Select Audio Playback
 2. Select any audio options  

###### Expected Result
 Play the audio selected

###### Actual Result
 Crash of the app

 I have tested in others devices, including tablets with API below 23 with no problem, it seems that the problem only occurs with API 23.

> 07-06 15:07:23.546 3588-3596/com.devbrackets.android.exomediademo E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                java.lang.Throwable: Explicit termination method 'close' not called
                                                                                    at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                                    at java.io.FileOutputStream.<init>(FileOutputStream.java:89)
                                                                                    at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                                    at com.android.okhttp.okio.Okio.sink(Okio.java:174)
                                                                                    at com.android.okhttp.internal.io.FileSystem$1.sink(FileSystem.java:49)
                                                                                    at com.android.okhttp.internal.DiskLruCache$Editor.newSink(DiskLruCache.java:876)
                                                                                    at com.android.okhttp.Cache$CacheRequestImpl.<init>(Cache.java:410)
                                                                                    at com.android.okhttp.Cache.put(Cache.java:236)
                                                                                    at com.android.okhttp.Cache.-wrap0(Cache.java)
                                                                                    at com.android.okhttp.Cache$1.put(Cache.java:142)
                                                                                    at com.android.okhttp.internal.http.HttpEngine.maybeCache(HttpEngine.java:554)
                                                                                    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:826)
                                                                                    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
                                                                                    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
                                                                                    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
                                                                                    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
                                                                                    at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:191)
                                                                                    at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                    at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:824)
                                                                                    at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by brianwernick** [comment]
This is just a strict mode setting, remove the `penaltyDeath()` in the `App.java`.  The resource is an issue within the ExoPlayer itself
