### ISSUE TITLE
StrictMode error about leaked Closable object

### ISSUE THREAD

**Issue by ehehhh** [brianwernick/ExoMedia#277]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 1. Set release on detach from window to `false` 
 2. call release() 

###### Expected Result
No Strict Mode errors about leaked closable objects
###### Actual Result
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               `java.lang.Throwable: Explicit termination method 'release' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at android.view.Surface.setNativeObjectLocked(Surface.java:459)
                                                                   at android.view.Surface.<init>(Surface.java:145)
                                                                   at com.devbrackets.android.exomedia.core.video.ExoVideoView$EMExoVideoSurfaceTextureListener.onSurfaceTextureAvailable(ExoVideoView.java:276)`

**Comment by brianwernick** [comment]
See #258

**Comment by ehehhh** [comment]
Thanks, man :+1:

**Comment by se-bastiaan** [comment]
Doesn't mean that you need to open a completely new issue. Brian could've just reopened this one.
