### ISSUE TITLE
Error inflating class android.support.design.widget.CollapsingToolbarLayout

### ISSUE THREAD

**Issue by jyh149129** [brianwernick/ExoMedia#286]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.1`
 - Device OS version: `5.0.2`
 - Devide Manufacturer: `Xiaomi`
 - Device Name: `MI2S`
 
###### Reproduction Steps
1、just add exomedia to gradle dependencies then app is crash
2、remove exomedia from gradle dependencies , anything is fine.
###### Expected Result
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxxx}: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
                                                                at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5238)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)
                                                             Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class android.support.design.widget.CollapsingToolbarLayout
                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:920)
                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
......................................
###### Actual Result

sorry my bad english!

**Comment by se-bastiaan** [comment]
This problem is not in ExoMedia, since it doesn't use any `CollapsingToolbarLayout`. Make sure your support library version is matching. It should be version 24.0.0.

**Comment by jyh149129** [comment]
i changed support version to 24.0 ,it's workd
thanks
