### ISSUE TITLE
Android Tv Leanback

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#287]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.0`
 - Devide Manufacturer: `Emulator`
 - Device Name: `Android Tv (720p)`
 
###### Reproduction Steps
 0.  Select any video
 1. Play video

###### Expected Result

Normal playback

###### Actual Result

Keeps buffering video

Hi, i'm trying to watch a video with the Android Emulator but i'm not able to get the playback. I've checked the Exoplayer `playbackState` but it never reachs `STATE_READY`. The states reported are:

```
STATE_PREPARING
STATE_PREPARING
STATE_BUFFERING
STATE_IDLE
```
Is there any setup that i could be missing? Thanks!!

**Comment by se-bastiaan** [comment]
Reproduction is in the demo app?

**Comment by billyjoker** [comment]
Yes, i've executed the master on emulator and i'tried perform like in a device.

**Comment by billyjoker** [comment]
It seems to be something related with the MediaCodec component, i see `MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6`. Logs:

```
07-22 12:17:02.542    1830-1830/com.devbrackets.android.exomediademo I/art﹕ Not late-enabling -Xcheck:jni (already on)
07-22 12:17:02.964    1830-1830/com.devbrackets.android.exomediademo W/art﹕ Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-22 12:17:03.183    1830-1845/com.devbrackets.android.exomediademo I/art﹕ Background partial concurrent mark sweep GC freed 958(87KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1008KB/2032KB, paused 1.005ms total 119.685ms
07-22 12:17:03.479    1830-1851/com.devbrackets.android.exomediademo I/OpenGLRenderer﹕ Initialized EGL, version 1.4
07-22 12:17:03.658    1830-1851/com.devbrackets.android.exomediademo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-22 12:17:03.659    1830-1851/com.devbrackets.android.exomediademo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6dd8800, error=EGL_SUCCESS
07-22 12:17:09.616    1830-1840/com.devbrackets.android.exomediademo W/art﹕ Suspending all threads took: 16.032ms
07-22 12:17:13.056    1830-1851/com.devbrackets.android.exomediademo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-22 12:17:13.056    1830-1851/com.devbrackets.android.exomediademo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa638c720, error=EGL_SUCCESS
07-22 12:17:15.338    1830-1830/com.devbrackets.android.exomediademo I/ExoPlayerImpl﹕ Init 1.5.9
07-22 12:17:15.473    1830-1845/com.devbrackets.android.exomediademo W/art﹕ Suspending all threads took: 9.120ms
07-22 12:17:15.564    1830-1830/com.devbrackets.android.exomediademo W/Settings﹕ Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-22 12:17:15.637    1830-1845/com.devbrackets.android.exomediademo I/art﹕ Background partial concurrent mark sweep GC freed 1230(104KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 1845KB/3MB, paused 14.964ms total 46.788ms
07-22 12:17:15.640    1830-1851/com.devbrackets.android.exomediademo W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-22 12:17:15.646    1830-1851/com.devbrackets.android.exomediademo W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6df42a0, error=EGL_SUCCESS
07-22 12:17:15.648    1830-1845/com.devbrackets.android.exomediademo W/art﹕ Suspending all threads took: 9.845ms
07-22 12:17:20.752    1830-1830/com.devbrackets.android.exomediademo I/Choreographer﹕ Skipped 298 frames!  The application may be doing too much work on its main thread.
07-22 12:17:21.036    1830-2235/com.devbrackets.android.exomediademo I/VideoCapabilities﹕ Unsupported profile 4 for video/mp4v-es
07-22 12:17:21.054    1830-2291/com.devbrackets.android.exomediademo I/OMXClient﹕ Using client-side OMX mux.
07-22 12:17:21.058    1830-2291/com.devbrackets.android.exomediademo E/OMXNodeInstance﹕ OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
07-22 12:17:21.058    1830-2291/com.devbrackets.android.exomediademo E/ACodec﹕ [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -2147483648
07-22 12:17:21.130    1830-2295/com.devbrackets.android.exomediademo I/OMXClient﹕ Using client-side OMX mux.
07-22 12:17:21.175    1830-2296/com.devbrackets.android.exomediademo I/SoftAAC2﹕ limiting to stereo output
07-22 12:17:21.186    1830-2292/com.devbrackets.android.exomediademo E/SoftAVC﹕ Decoder failed: -2
07-22 12:17:21.187    1830-2291/com.devbrackets.android.exomediademo E/ACodec﹕ [OMX.google.h264.decoder] ERROR(0x80001001)
07-22 12:17:21.188    1830-2291/com.devbrackets.android.exomediademo E/ACodec﹕ signalError(omxError 0x80001001, internalError -2147483648)
07-22 12:17:21.188    1830-2290/com.devbrackets.android.exomediademo E/MediaCodec﹕ Codec reported err 0x80001001, actionCode 0, while in state 6
07-22 12:17:21.201    1830-2235/com.devbrackets.android.exomediademo E/ExoPlayerImplInternal﹕ Internal runtime error.
    java.lang.IllegalStateException
            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:890)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by brianwernick** [comment]
Does your emulator actually have network access?  Many times the TV emulator will not retain network access over WiFi (ethernet typically works)

**Comment by billyjoker** [comment]
As i've [investigated](https://github.com/googlesamples/androidtv-Leanback/issues/50) it seems that the Tv emulator has problems with network. I have not found solutions for this issue. Have you tried to play any video with Android Tv?

**Comment by se-bastiaan** [comment]
I know that ExoMedia 2.5.6 works on the Nexus Player, I used it in [one of my projects](https://github.com/se-bastiaan/TVNL-AndroidTV). So I'm assuming that 3.x also works, since it's fundamentals are still the same: ExoPlayer.

**Comment by billyjoker** [comment]
The fact is that the Emulator (with network) works fine with mobile devices, but is not working with Android Tv. It would be very interesting that one of you could test this scenario. I can not test with a real device just now.

**Comment by brianwernick** [comment]
I have an ADT-1 that I test with before I release a version, which is why I'm thinking it is an Emulator issue (I also just tested it last night and everything worked fine)
