### ISSUE TITLE
Support ExoPlayer 1.5.2

### ISSUE THREAD

**Issue by tuanchauict** [brianwernick/ExoMedia#29]
It seems current version of ExoMedia uses ExoPlayer r1.4.2. My project add ExoPlayer r1.5.2 before I know ExoMedia. I just add 

    compile 'com.devbrackets.android:exomedia:2.3.1'

to `build.gradle` along with 

    compile 'com.google.android.exoplayer:exoplayer:r1.5.2'

It throw exception on runtime at this:

```
 Caused by: java.lang.NoSuchMethodError: No virtual method register()V in class Lcom/google/android/exoplayer/audio/AudioCapabilitiesReceiver; or its super classes (declaration of 'com.google.android.exoplayer.audio.AudioCapabilitiesReceiver' appears in /data/app/com.ffd.hg.xr.debug-1/base.apk)
                                                                       at com.devbrackets.android.exomedia.EMVideoView.setupExoPlayer(EMVideoView.java:213)
                                                                       at com.devbrackets.android.exomedia.EMVideoView.initView(EMVideoView.java:205)
```

**Comment by brianwernick** [comment]
You don't need to include the  `compile 'com.google.android.exoplayer:exoplayer:r1.5.2'` dependency in your build.gradle.  This is already added through transitive dependencies when you use ExoMedia.  Additionally, there is a newer version (2.4.0) of ExoMedia that you may want to use.

I've been pretty busy the last few weeks however I have already updated the source to use the 1.5.2 ExoPlayer version, but there are a few other bugs that I want to get fixed before I push a new release out .  I'm hoping that I will have enough time this weekend to do that.

**Comment by brianwernick** [comment]
I'm going to close this as I will be releasing an updated version shortly
