### ISSUE TITLE
H265 Issues.

### ISSUE THREAD

**Issue by euroclydon37** [brianwernick/ExoMedia#305]
I don't know if it's ExoMedia or ExoPlayer, but I can no longer play h265 encoded videos. I lost this functionality when I moved from VideoView to ExoMedia.

I'm running Android on an Odroid C2 SoC that has a hardware 265 decoder.

**Comment by brianwernick** [comment]
Please follow the issue template and post any stack traces or relevant logs. Otherwise I will close this issue as not enough information

**Comment by euroclydon37** [comment]
Sorry, I don't know why I didn't think to do that. The device is at the office, and I won't be back in until Tuesday. I'll post the log then. Thanks for responding so quickly.

**Comment by euroclydon37** [comment]
So I got to the office, today, and attempted h265 playback. Here's the log.

`09-06 16:05:34.531 5606-5606/com.spectiv.slave I/ExoPlayerImpl: Init 1.5.9
09-06 16:05:34.668 5606-8618/com.spectiv.slave I/OMXClient: Using client-side OMX mux.
09-06 16:05:34.689 5606-8618/com.spectiv.slave E/ACodec: [OMX.amlogic.hevc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
09-06 16:05:34.697 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
09-06 16:05:34.697 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
09-06 16:05:34.697 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
09-06 16:05:34.721 5606-8625/com.spectiv.slave I/OMXClient: Using client-side OMX mux.
09-06 16:05:34.743 5606-8625/com.spectiv.slave I/omx_core: OMX_Init 66 gInitCount=1
09-06 16:05:34.775 5606-8625/com.spectiv.slave V/AML_all_components: --------------------------------
                                                                     ARCH = arm
                                                                     author:aml.sh multi-media team
                                                                     branch name:   * jb-mr1-amlogic
                                                                     git version:   96d38667a09dc46794b45c9d9c1c7113097441cf 
                                                                     last changed:  Date: Tue Oct 27 14:43:58 2015 +0800
                                                                     build-time:     Tue Oct 27 14:45:01 CST 2015
                                                                     build-name:     jintao.xu
                                                                     uncommitted-file-num:0
                                                                     cd /mnt/fileroot/jintao.xu/5.1.p201
                                                                     hostname droid07
                                                                     --------------------------------
09-06 16:05:34.775 5606-8625/com.spectiv.slave V/OmxComponentManagerImpl: loadLibrary:228 Loading OMX library libOmxVideo.so.
09-06 16:05:34.776 5606-8625/com.spectiv.slave E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
09-06 16:05:34.776 5606-8625/com.spectiv.slave I/omx_core: Core library has 10 components
09-06 16:05:34.776 5606-8625/com.spectiv.slave E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
09-06 16:05:34.776 5606-8625/com.spectiv.slave E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
09-06 16:05:34.782 5606-8627/com.spectiv.slave I/SoftAAC2: limiting to stereo output
09-06 16:05:34.795 5606-8627/com.spectiv.slave I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
09-06 16:05:34.805 5606-8611/com.spectiv.slave I/AudioTrack: set(): 0xef0ce200 streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 16384, flags #0, notificationFrames 0, sessionId 0, transferType 3
09-06 16:05:35.141 5606-8618/com.spectiv.slave E/ACodec: [OMX.amlogic.hevc.decoder.awesome] ERROR(0x80001000)
09-06 16:05:35.141 5606-8618/com.spectiv.slave E/ACodec: signalError(omxError 0x80001000, internalError -2147483648)
09-06 16:05:35.141 5606-8617/com.spectiv.slave E/MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 6
09-06 16:05:35.308 5606-8611/com.spectiv.slave E/ExoPlayerImplInternal: Internal runtime error.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                            at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:890)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:512)
                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
09-06 16:05:35.440 5606-8618/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xef09c460
09-06 16:05:35.440 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4112040032 to native window
09-06 16:05:35.440 5606-8618/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xef09c400
09-06 16:05:35.440 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4110901008 to native window
09-06 16:05:35.440 5606-8618/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xef09c3a0
09-06 16:05:35.441 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4112041312 to native window
09-06 16:05:35.441 5606-8618/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xef09c2e0
09-06 16:05:35.441 5606-8618/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4102297408 to native window
09-06 16:05:35.552 5606-8611/com.spectiv.slave E/ExoPlayerImplInternal: Stop failed.
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_stop(Native Method)
                                                                            at android.media.MediaCodec.stop(MediaCodec.java:632)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:469)
                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:434)
                                                                            at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:289)
                                                                            at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:231)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.ensureDisabled(ExoPlayerImplInternal.java:661)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:562)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:551)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:528)
                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:247)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
09-06 16:05:35.553 5606-8646/com.spectiv.slave I/AudioTrack: ~AudioTrack, releasing session id from 5606 on behalf of 5606 mState/4
09-06 16:05:35.586 5606-8625/com.spectiv.slave I/omx_core: OMX_Deinit 96 gInitCount=0
`

**Comment by brianwernick** [comment]
Have you tried ExoMedia `3.0.2`?

**Comment by euroclydon37** [comment]
Just tried it. Here's the log.
`09-06 17:26:58.090 32300-32300/com.spectiv.slave I/ExoPlayerImpl: Init 1.5.10
09-06 17:26:58.292 32300-1766/com.spectiv.slave I/OMXClient: Using client-side OMX mux.
09-06 17:26:58.312 32300-1766/com.spectiv.slave E/ACodec: [OMX.amlogic.hevc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
09-06 17:26:58.322 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
09-06 17:26:58.322 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
09-06 17:26:58.322 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
09-06 17:26:58.334 32300-1769/com.spectiv.slave I/OMXClient: Using client-side OMX mux.
09-06 17:26:58.346 32300-1769/com.spectiv.slave I/omx_core: OMX_Init 66 gInitCount=1
09-06 17:26:58.533 32300-1769/com.spectiv.slave V/AML_all_components: --------------------------------
                                                                      ARCH = arm
                                                                      author:aml.sh multi-media team
                                                                      branch name:   * jb-mr1-amlogic
                                                                      git version:   96d38667a09dc46794b45c9d9c1c7113097441cf 
                                                                      last changed:  Date: Tue Oct 27 14:43:58 2015 +0800
                                                                      build-time:     Tue Oct 27 14:45:01 CST 2015
                                                                      build-name:     jintao.xu
                                                                      uncommitted-file-num:0
                                                                      cd /mnt/fileroot/jintao.xu/5.1.p201
                                                                      hostname droid07
                                                                      --------------------------------
09-06 17:26:58.533 32300-1769/com.spectiv.slave V/OmxComponentManagerImpl: loadLibrary:228 Loading OMX library libOmxVideo.so.
09-06 17:26:58.533 32300-1769/com.spectiv.slave E/omx_video: amvenc_avc open failed!set default instance number as 1,ret=-1,Permission denied(13)
09-06 17:26:58.533 32300-1769/com.spectiv.slave I/omx_core: Core library has 10 components
09-06 17:26:58.533 32300-1769/com.spectiv.slave E/OMXMaster: A component of name 'OMX.google.h264.decoder' already exists, ignoring this one.
09-06 17:26:58.533 32300-1769/com.spectiv.slave E/OMXMaster: A component of name 'OMX.google.alac.decoder' already exists, ignoring this one.
09-06 17:26:58.540 32300-1774/com.spectiv.slave I/SoftAAC2: limiting to stereo output
09-06 17:26:58.541 32300-1774/com.spectiv.slave I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
09-06 17:26:58.566 32300-1754/com.spectiv.slave I/AudioTrack: set(): 0xef0d0a00 streamType -1, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 16384, flags #0, notificationFrames 0, sessionId 0, transferType 3
09-06 17:26:58.643 32300-1766/com.spectiv.slave E/ACodec: [OMX.amlogic.hevc.decoder.awesome] ERROR(0x80001000)
09-06 17:26:58.643 32300-1766/com.spectiv.slave E/ACodec: signalError(omxError 0x80001000, internalError -2147483648)
09-06 17:26:58.644 32300-1765/com.spectiv.slave E/MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 6
09-06 17:26:58.646 32300-1754/com.spectiv.slave E/ExoPlayerImplInternal: Internal runtime error.
                                                                         java.lang.IllegalStateException
                                                                             at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                             at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:919)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:528)
                                                                             at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
09-06 17:26:58.809 32300-1766/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf4d08a60
09-06 17:26:58.809 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4110900368 to native window
09-06 17:26:58.810 32300-1766/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf4ee1220
09-06 17:26:58.810 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4102297648 to native window
09-06 17:26:58.810 32300-1766/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf4ee11c0
09-06 17:26:58.810 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4102298608 to native window
09-06 17:26:58.815 32300-1766/com.spectiv.slave E/Surface: getSlotFromBufferLocked: unknown buffer: 0xf4ee10a0
09-06 17:26:58.815 32300-1766/com.spectiv.slave W/ACodec: [OMX.amlogic.hevc.decoder.awesome] can not return buffer 4110900288 to native window
09-06 17:26:58.890 32300-1754/com.spectiv.slave E/ExoPlayerImplInternal: Stop failed.
                                                                         java.lang.IllegalStateException
                                                                             at android.media.MediaCodec.native_stop(Native Method)
                                                                             at android.media.MediaCodec.stop(MediaCodec.java:632)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.releaseCodec(MediaCodecTrackRenderer.java:485)
                                                                             at com.google.android.exoplayer.MediaCodecTrackRenderer.onDisabled(MediaCodecTrackRenderer.java:447)
                                                                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onDisabled(MediaCodecVideoTrackRenderer.java:289)
                                                                             at com.google.android.exoplayer.TrackRenderer.disable(TrackRenderer.java:231)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.ensureDisabled(ExoPlayerImplInternal.java:659)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.stopAndDisable(ExoPlayerImplInternal.java:560)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:549)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:526)
                                                                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:245)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
09-06 17:26:58.891 32300-1790/com.spectiv.slave I/AudioTrack: ~AudioTrack, releasing session id from 32300 on behalf of 32300 mState/4
09-06 17:26:58.916 32300-1769/com.spectiv.slave I/omx_core: OMX_Deinit 96 gInitCount=0`

**Comment by brianwernick** [comment]
This looks like an ExoPlayer issue, I would recommend you posting an Issue on that repository or including an example file here so I can open an issue.

**Comment by euroclydon37** [comment]
Ok. Thanks for looking into it. I'll go post over there.
