### ISSUE TITLE
Bug run audio android 6.0 sony XA

### ISSUE THREAD

**Issue by buitienhd91** [brianwernick/ExoMedia#320]
hi. i am not run audio android 6.0 
09-23 15:07:56.892 24505-25236/com.devbrackets.android.exomediademo W/MessageQueue: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {83b1d43} sending message to a Handler on a dead thread
                                                                                    java.lang.IllegalStateException: Handler (com.google.android.exoplayer.upstream.Loader$LoadTask) {83b1d43} sending message to a Handler on a dead thread
                                                                                        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:555)
                                                                                        at android.os.Handler.enqueueMessage(Handler.java:707)
                                                                                        at android.os.Handler.sendMessageAtTime(Handler.java:609)
                                                                                        at android.os.Handler.sendMessageDelayed(Handler.java:579)
                                                                                        at android.os.Handler.sendEmptyMessageDelayed(Handler.java:543)
                                                                                        at android.os.Handler.sendEmptyMessage(Handler.java:528)
                                                                                        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:225)
                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)

help me!
thanks.

**Comment by brianwernick** [comment]
See #42  and https://github.com/google/ExoPlayer/issues/426
