### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by DoaiNguyen** [brianwernick/ExoMedia#331]
When i'm play a m3u8 link, after time about 10s...

10-13 15:54:16.084 28421-28759/com.devbrackets.android.exomediademo E/OMXNodeInstance: OMX_GetExtensionIndex failed
10-13 15:54:16.092 28421-28760/com.devbrackets.android.exomediademo E/SoftAVC: Decoder failed: -2
10-13 15:54:16.092 28421-28759/com.devbrackets.android.exomediademo E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
10-13 15:54:16.092 28421-28759/com.devbrackets.android.exomediademo E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -2147483648)
10-13 15:54:16.100 28421-28477/com.devbrackets.android.exomediademo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                             java.lang.IllegalStateException
                                                                                                 at android.media.MediaCodec.dequeueOutputBuffer(Native Method)
                                                                                                 at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:922)
                                                                                                 at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:528)
                                                                                                 at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                                 at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                                 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                                 at android.os.HandlerThread.run(HandlerThread.java:60)
                                                                                                 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by se-bastiaan** [comment]
Please use the issue template.

**Comment by platinum7919** [comment]
had a similar issue
```

03-15 15:31:37.396 E/ExoPlayerImplInternal: Internal runtime error.
                                            java.lang.IllegalStateException
                                                at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:922)
                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:528)
                                                at com.charaku.popsical.tv.player.DashRendererBuilder$AsyncRendererBuilder$1.doSomeWork(DashRendererBuilder.java:241)
                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                at android.os.Looper.loop(Looper.java:148)
                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
03-15 15:31:37.397 E/EventLogger: playerFailed [0.80]
                                  com.google.android.exoplayer.ExoPlaybackException: java.lang.IllegalStateException
                                      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:244)
                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                      at android.os.Looper.loop(Looper.java:148)
                                      at android.os.HandlerThread.run(HandlerThread.java:61)
                                      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                   Caused by: java.lang.IllegalStateException
                                      at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                      at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                      at com.google.android.exoplayer.MediaCodecTrackRenderer.drainOutputBuffer(MediaCodecTrackRenderer.java:922)
                                      at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:528)
                                      at com.charaku.popsical.tv.player.DashRendererBuilder$AsyncRendererBuilder$1.doSomeWork(DashRendererBuilder.java:241)
                                      at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                      at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                      at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                      at android.os.Handler.dispatchMessage(Handler.java:98) 
                                      at android.os.Looper.loop(Looper.java:148) 
                                      at android.os.HandlerThread.run(HandlerThread.java:61) 
                                      at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

**Comment by platinum7919** [comment]
When trying to play this video

URL Base64 encoded (sorry I don't want to make the URL searchable, just use a decoder online or something to get the actual URL)

`aHR0cHM6Ly92LnBvcHNpY2FsLnR2LzQ3MDM3MF85ZTgxZGRmM2Q3NWExZmU0YmI1Y2RkOTZiYTQ4YTQzMy80NzAzNzAubXBk`
