### ISSUE TITLE
Binary XML file: Error inflating class com.devbrackets.android.exomedia.EMVideoView

### ISSUE THREAD

**Issue by alexWr** [brianwernick/ExoMedia#346]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- ExoMedia version: `3.0.5`
- Device OS version: `4.1.2`
- Devide Manufacturer: `Lenovo`
- Device Name: `K900`

I have this issue when I build your lib with gradle 2.2.2 and add as .aar library to my project. 

```
FATAL EXCEPTION: main
  android.view.InflateException: Binary XML file line #14: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
      at android.view.LayoutInflater.createView(LayoutInflater.java:613)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
      at com.lunchbreakideas.chapel.ui.fragment.famtv.FamTvFragment.onCreateView(FamTvFragment.java:41)
      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
      at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
      at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
      at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
      at android.view.View.measure(View.java:15536)
      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:645)
      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:425)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
      at android.view.View.measure(View.java:15536)
      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:645)
      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:425)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
      at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
      at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
      at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2185)
      at android.view.View.measure(View.java:15536)
      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1881)
      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1095)
    at android.view.ViewRootImpl.performTraversals(ViewRootImp
```

When I add lib as compile 'com.devbrackets.android:exomedia:3.0.5' everything works fine. Thanks in advance

**Comment by brianwernick** [comment]
Are you saying using `compile 'com.devbrackets.android:exomedia:3.0.5@aar'` isn't working?  If that's the case it isn't downloading the transitive dependencies necessary so you would need to do
```
compile ('com.devbrackets.android:exomedia:3.0.5@aar') {
    transitive = true
}
```

**Comment by alexWr** [comment]
No no,  when I am using compile 'com.devbrackets.android:exomedia:3.0.5@aar' everything is ok. This issue appear when I build .aar lib and add as module dependency

**Comment by se-bastiaan** [comment]
You're probably still missing the dependencies, since those are not included in the `.aar`. If you want to use the library from source then why not use the project directly as dependency? As in, make a module in your Android Studio project and reference it like `compile project(":exomedia")`.

**Comment by brianwernick** [comment]
When ExoMedia is a module dependency you should be able to follow the demo module.

**Comment by alexWr** [comment]
Ok, thanks. I try add exomedia project as dependency.

**Comment by brianwernick** [comment]
@alexWr Did you resolve this ?

**Comment by alexWr** [comment]
Yes, thanks. I added project and builded it. You can close this issue
