### ISSUE TITLE
Error while setVideoPath

### ISSUE THREAD

**Issue by marekSeda** [brianwernick/ExoMedia#347]
Hi,
when I call videoView.setVideoPath(String path) I get error.

```
MessageQueue: Handler (android.os.Handler) {609d304} sending message to a Handler on a dead thread
  java.lang.IllegalStateException: Handler (android.os.Handler) {609d304} sending message to a Handler on a dead thread
      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
      at android.os.Handler.enqueueMessage(Handler.java:631)
      at android.os.Handler.sendMessageAtTime(Handler.java:600)
      at android.os.Handler.sendMessageDelayed(Handler.java:570)
      at android.os.Handler.sendMessage(Handler.java:507)
      at android.os.Message.sendToTarget(Message.java:416)
      at com.google.android.exoplayer.ExoPlayerImplInternal.seekTo(ExoPlayerImplInternal.java:146)
      at com.google.android.exoplayer.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:146)
      at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.seekTo(EMExoPlayer.java:330)
      at com.devbrackets.android.exomedia.core.video.ExoVideoView.setVideoUri(ExoVideoView.java:104)
      at com.devbrackets.android.exomedia.core.video.ExoVideoView.setVideoUri(ExoVideoView.java:88)
      at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setVideoURI(EMVideoView.java:260)
      at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setVideoPath(EMVideoView.java:289)
      at eu.ugomedia.MainActivity.setupVideoView(MainActivity.java:101)
      at eu.ugomedia.MainActivity.mediaToPlayChanged(MainActivity.java:237)
      at eu.ugomedia.MediaManager.startArrayPlay(MediaManager.java:168)
      at eu.ugomedia.MediaManager.getVideoToPlay(MediaManager.java:112)
      at eu.ugomedia.MediaManager.checkChanges(MediaManager.java:91)
      at eu.ugomedia.MediaManager$1.run(MediaManager.java:57)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5221)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```
Please why I getting this error ?

**Comment by brianwernick** [comment]
This isn't #42?
