### ISSUE TITLE
OutofMemory error in exoplayer buffer

### ISSUE THREAD

**Issue by jdprajapati** [brianwernick/ExoMedia#351]
Hi,

1) My local chunk is not playing longer, its size is 1.1GB.  its working fine while I am playing live stream but when I am using from local storage its crashed after few mins and throwing the exception of outofmemory.
FYI, I have set large heap true in manifest.

11-10 15:43:43.746 7691-8522/c.a.login E/LoadTask: Unexpected error loading stream
                                                   java.lang.OutOfMemoryError: Failed to allocate a 144016 byte allocation with 119936 free bytes and 117KB until OOM
                                                       at com.google.android.exoplayer.extractor.RollingSampleBuffer$InfoQueue.commitSample(RollingSampleBuffer.java:626)
                                                       at com.google.android.exoplayer.extractor.RollingSampleBuffer.commitSample(RollingSampleBuffer.java:429)
                                                       at com.google.android.exoplayer.extractor.DefaultTrackOutput.sampleMetadata(DefaultTrackOutput.java:266)
                                                       at com.google.android.exoplayer.extractor.ts.AdtsReader.readSample(AdtsReader.java:307)
                                                       at com.google.android.exoplayer.extractor.ts.AdtsReader.consume(AdtsReader.java:120)
                                                       at com.google.android.exoplayer.extractor.ts.TsExtractor$PesReader.consume(TsExtractor.java:643)
                                                       at com.google.android.exoplayer.extractor.ts.TsExtractor.read(TsExtractor.java:220)
                                                       at com.google.android.exoplayer.hls.HlsExtractorWrapper.read(HlsExtractorWrapper.java:238)
                                                       at com.google.android.exoplayer.hls.TsChunk.load(TsChunk.java:116)
                                                       at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)

2) Video showing green screen and audio is working fine, my stream is H265.

Can you please check this problem and give me the solution.

Thanks in advance.

**Comment by protoss5482** [comment]
E/AndroidRuntime: FATAL EXCEPTION: ExoPlayerImplInternal:Handler
    Process: my.package.name, PID: 27284
    java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 38936 free bytes and 38KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
        at com.google.android.exoplayer2.util.ParsableByteArray.<init>(ParsableByteArray.java:45)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:255)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:225)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:206)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:190)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.<init>(FragmentedMp4Extractor.java:182)
        at com.google.android.exoplayer2.extractor.DefaultExtractorsFactory.createExtractors(DefaultExtractorsFactory.java:211)
        at com.google.android.exoplayer2.source.ExtractorMediaSource.createPeriod(ExtractorMediaSource.java:384)
        at com.google.android.exoplayer2.MediaPeriodHolder.<init>(MediaPeriodHolder.java:82)
        at com.google.android.exoplayer2.MediaPeriodQueue.enqueueNextMediaPeriod(MediaPeriodQueue.java:149)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.maybeUpdateLoadingPeriod(ExoPlayerImplInternal.java:1530)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.updatePeriods(ExoPlayerImplInternal.java:1399)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:513)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
