### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by httpdispatch** [brianwernick/ExoMedia#353]
- [ V] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `5.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 4`
 
###### Reproduction Steps
reuse player for few times by calling setDataSource or should i call release every time?

###### Expected Result
No memory leak

###### Actual Result
Memory leak

```
Activity com.example.MyActivity has leaked IntentReceiver com.google.android.exoplayer.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver@dd6b62c that was originally registered here. Are you missing a call to unregisterReceiver()?
	   android.app.IntentReceiverLeaked: Activity com.example.MyActivity has leaked IntentReceiver com.google.android.exoplayer.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver@dd6b62c that was originally registered here. Are you missing a call to unregisterReceiver()?
		   at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:903)
		   at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:704)
		   at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1643)
		   at android.app.ContextImpl.registerReceiver(ContextImpl.java:1623)
		   at android.app.ContextImpl.registerReceiver(ContextImpl.java:1617)
		   at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
		   at com.google.android.exoplayer.audio.AudioCapabilitiesReceiver.register(AudioCapabilitiesReceiver.java:74)
		   at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.replaceRenderBuilder(EMExoPlayer.java:172)
		   at com.devbrackets.android.exomedia.core.audio.ExoMediaPlayer.setDataSource(ExoMediaPlayer.java:89)
		   at com.devbrackets.android.exomedia.core.audio.ExoMediaPlayer.setDataSource(ExoMediaPlayer.java:81)
		   at com.devbrackets.android.exomedia.EMAudioPlayer.setDataSource(EMAudioPlayer.java:116)
```

**Comment by brianwernick** [comment]
Calling `setDataSource()` multiple times should work, you don't need to call `release()` as that performs other functionality that you don't want.
Currently we are only creating a receiver once and re-using that until the EMExoPlayer is released, maybe we should just register a new one for each new datasource (and unregister the old one).

**Comment by httpdispatch** [comment]
Shouldn't these lines https://github.com/brianwernick/ExoMedia/blob/2b3d7bca106bfd6aa6e5343a2c1166b3c9ee1e09/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java#L170-L173

contain audioCapabilitiesReceiver.unregister call before registering new one? Same as here

https://github.com/brianwernick/ExoMedia/blob/2b3d7bca106bfd6aa6e5343a2c1166b3c9ee1e09/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/EMExoPlayer.java#L381-L384

**Comment by brianwernick** [comment]
Yep, the first link is the section that needs to be updated to release the receiver and always create a new one (if the renderBuilder != null)

**Comment by jaspreet-android** [comment]
*The issue is still there for below lib version:-*
compile 'com.longtailvideo.jwplayer:jwplayer-core:2.6.3+14'
compile 'com.longtailvideo.jwplayer:jwplayer-common:2.6.3+14'

```
Activity com.example.activities.MainActivity has leaked IntentReceiver com.google.android.exoplayer.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver@7425c23 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                        android.app.IntentReceiverLeaked: Activity com.example.activities.MainActivity has leaked IntentReceiver com.google.android.exoplayer.audio.AudioCapabilitiesReceiver$HdmiAudioPlugBroadcastReceiver@7425c23 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                            at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
                                                                            at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
                                                                            at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
                                                                            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
                                                                            at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
                                                                            at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
                                                                            at com.google.android.exoplayer.audio.AudioCapabilitiesReceiver.register(SourceFile:74)
                                                                            at com.longtailvideo.jwplayer.c.e.<init>(SourceFile:217)
                                                                            at com.longtailvideo.jwplayer.core.g.a(SourceFile:172)
                                                                            at com.longtailvideo.jwplayer.JWPlayerView.a(SourceFile:220)
                                                                            at com.longtailvideo.jwplayer.JWPlayerView.<init>(SourceFile:191)
                                                                            at com.example.adapter.MyVideoAdapter$VideoItem.setData(MyVideoAdapter.java:345)
```

Here is my code:-
```Java
if (player == null) {
    PlayerConfig playerConfig = new PlayerConfig.Builder()
            .file(vod_url)
            .autostart(true)
            .controls(true)
            //.preload(false)
            .relatedAutoPlayTimer(1)
            .mute(true)
            .repeat(true)
            .build();
    try {
        if (playerConfig != null) {
            player = new JWPlayerView(context, playerConfig); // This is the line which receives above error warning, everytime I close my application.
            player.setMinimumHeight(playerContainer.getMinimumHeight());
            playerContainer.addView(player);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
final PlaylistItem video = new PlaylistItem(vod_url);
player.load(video);
player.play();
```

**Comment by hyunjkim** [comment]
Have you tried implementing your lifecycle activity like this: 

`@Override
protected void onResume() {
    // Let JW Player know that the app has returned from the background
    super.onResume();
    playerView.onResume();
}

@Override
protected void onPause() {
    // Let JW Player know that the app is going to the background
    playerView.onPause();
    super.onPause();
}

@Override
protected void onDestroy() {
    // Let JW Player know that the app is being destroyed
    playerView.onDestroy();
    super.onDestroy();
}`

For more info: [https://developer.jwplayer.com/sdk/android/docs/developer-guide/usage/jwplayer-view/#activity-lifecycle-handling](https://developer.jwplayer.com/sdk/android/docs/developer-guide/usage/jwplayer-view/#activity-lifecycle-handling)
