### ISSUE TITLE
Exoplayer Error

### ISSUE THREAD

**Issue by jdprajapati** [brianwernick/ExoMedia#354]
Internal track renderer error.
                                                                com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, MediaFormat(null, video/avc, -1, -1, 704, 576, -1, 1.0, -1, -1, null, -1, false, -1, -1, -1, -1, -1)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:427)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800)
                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540)
                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523)
                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)

**Comment by jdprajapati** [comment]
Can you update the Exoplayer inside your build? This is cause from Exoplayer and its fixed but in your project you are using old version exoplayer.

Thanks in advance.

**Comment by brianwernick** [comment]
ExoMedia is using the most recent 1.x version of the ExoPlayer (`1.5.12` specifically). If you are looking for an update to ExoPlayer 2.x see #311
