### ISSUE TITLE
ANR when the surface of EMExoPlayer is getting destroyed

### ISSUE THREAD

**Issue by mblcdr** [brianwernick/ExoMedia#380]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Device, OS and ...:
 - ExoMedia version: `3.1.0`
 - Device OS version: `Mostly on 4.4.2 and 4.1.2`
 - Device Manufacturer: `Mostly Huawei`
 - Device Name: `CHM-U01, Che2-L11, ...`

###### Stacktrace:
```Java
Caused by ANRError: main (state = WAITING)
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:364)
       at com.google.android.exoplayer.ExoPlayerImplInternal.blockingSendMessage(ExoPlayerImplInternal.java:172)
       at com.google.android.exoplayer.ExoPlayerImpl.blockingSendMessage(ExoPlayerImpl.java:166)
       at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.pushSurface(EMExoPlayer.java:685)
       at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.blockingClearSurface(EMExoPlayer.java:210)
       at com.devbrackets.android.exomedia.core.video.ExoVideoView$EMExoVideoSurfaceTextureListener.onSurfaceTextureDestroyed(ExoVideoView.java:290)
       at android.view.TextureView.destroySurface(TextureView.java:239)
       at android.view.TextureView.destroyHardwareResources(TextureView.java:344)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2351)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.destroyResources(HardwareRenderer.java:2358)
       at android.view.HardwareRenderer$Gl20Renderer.access$800(HardwareRenderer.java:1935)
       at android.view.HardwareRenderer$Gl20Renderer$2.run(HardwareRenderer.java:2343)
       at android.view.HardwareRenderer$Gl20Renderer.safelyRun(HardwareRenderer.java:2294)
       at android.view.HardwareRenderer$Gl20Renderer.destroyHardwareResources(HardwareRenderer.java:2337)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1048)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5952)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
       at android.view.Choreographer.doCallbacks(Choreographer.java:600)
       at android.view.Choreographer.doFrame(Choreographer.java:569)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5291)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
 

This ANR happened 403 times for 187 unique users in past 7 days in our app. Also it occurs in different forms (depending on how the player is used), such as:

```Java
Caused by ANRError: main (state = WAITING)
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:364)
       at com.google.android.exoplayer.ExoPlayerImplInternal.blockingSendMessage(ExoPlayerImplInternal.java:172)
       at com.google.android.exoplayer.ExoPlayerImpl.blockingSendMessage(ExoPlayerImpl.java:166)
       at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.pushSurface(EMExoPlayer.java:685)
       at com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer.blockingClearSurface(EMExoPlayer.java:210)
       at com.devbrackets.android.exomedia.core.video.ExoVideoView$EMExoVideoSurfaceTextureListener.onSurfaceTextureDestroyed(ExoVideoView.java:290)
       at android.view.TextureView.destroySurface(TextureView.java:239)
       at android.view.TextureView.access$000(TextureView.java:105)
       at android.view.TextureView$1.run(TextureView.java:220)
       at android.view.HardwareRenderer$Gl20Renderer.safelyRun(HardwareRenderer.java:2294)
       at android.view.View.executeHardwareAction(View.java:12517)
       at android.view.TextureView.onDetachedFromWindow(TextureView.java:217)
       at android.view.View.dispatchDetachedFromWindow(View.java:12658)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3865)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3838)
       at android.view.ViewGroup.removeView(ViewGroup.java:3770)
       ...
```
Let me know if I can provide more information so that we can resolve this issue.

**Comment by brianwernick** [comment]
What is the setup in the Activity/Fragment for the `EMVideoView`?

**Comment by mblcdr** [comment]
This is how I create the `videoView`:
```Java
videoView = new EMVideoView(context);
videoView.setLayoutParams(new FrameLayout.LayoutParams(
        FrameLayout.LayoutParams.MATCH_PARENT, FrameLayout.LayoutParams.WRAP_CONTENT));
videoView.setReleaseOnDetachFromWindow(false);
videoView.setOnCompletionListener(this);
videoView.setOnErrorListener(this);
videoView.setMeasureBasedOnAspectRatioEnabled(true);
VideoControlsMobile vcm = new VideoControlsMobile(context);
videoView.setControls(vcm);
videoView.showControls();
```

Then I add the `videoView` to a `FrameLayout`. This `videoView` is shared between some containers. When it is needed in another container I call `stop()` and then remove it from the previous container, then add it to requesting container. (That's why I used `setReleaseOnDetachFromWindow(false)`)

Finally in `onDestroy()` of the activity I call `stop()` and then I remove the `videoView` from container and call `release()` on it.

**Comment by brianwernick** [comment]
Are you still seeing this issue with the 4.x release?
