### ISSUE TITLE
Question: How to render video with license using EMVideoView?

### ISSUE THREAD

**Issue by adelumban-sp** [brianwernick/ExoMedia#396]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5`

I'm trying to play a video with license, and could not render the video.

sample Dash with license found in tutorial [here](https://www.axinom.com/setting-up-a-simple-dash-js-player-for-multi-drm-playback/)

```
        final String vidURL = "http://level3-cdn.axprod.net/demo/manifestprot.ism/.mpd";
        final String licenseURL = "http://axpr-wv-fe.cloudapp.net:8080/LicensingService";
```

Using  test player from [here](http://bitmovin.com/mpeg-dash-hls-drm-test-player/)
the two URLs are alive and working.

when I tried to use the links above in EMVideoView I get an error.
Do you have an example on how to implement this?

###### Reproduction Steps

```
private void init() {
        final String vidURL = "http://level3-cdn.axprod.net/demo/manifestprot.ism/.mpd";
        final String licenseURL = "http://axpr-wv-fe.cloudapp.net:8080/LicensingService";

        emVideoView = (EMVideoView) findViewById(R.id.video_view);
        emVideoView.setOnPreparedListener(this);

        emVideoView.setDrmProvider( new DrmProvider(){
            @Nullable
            @Override
            public MediaDrmCallback getDefaultCallback() {

                MediaDrmCallback mdcallback = new MediaDrmCallback() {
                    @Override
                    public byte[] executeProvisionRequest(UUID uuid, ExoMediaDrm.ProvisionRequest request) throws Exception {
                        return Util.executePost(licenseURL, request.getData(), null);
                    }

                    @Override
                    public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
                        return Util.executePost(licenseURL, request.getData(), null);
                    }
                };

                return mdcallback;
            }
        });

        emVideoView.setVideoURI(Uri.parse(vidURL));
    
    }

  @Override
    public void onPrepared() {
        Log.d("vimondplayer:", " started");
        //Starts the video playback as soon as it is ready
        emVideoView.start();
    }
```
###### Expected Result
normal video rendering

###### Actual Result
```
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

Internal track renderer error.
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(1, video/avc, -1, -1, 512, 288, 0, 1.0, -1, -1, null, -1, false, 1564, 880, -1, -1, -1)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:427)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800)
                                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523)
                                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128)
                                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432)
                                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                                 Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, MediaFormat(1, video/avc, -1, -1, 512, 288, 0, 1.0, -1, -1, null, -1, false, 1564, 880, -1, -1, -1)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413) 
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800) 
                                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540) 
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523) 
                                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128) 
                                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432) 
                                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                                                                                                 Caused by: android.media.MediaCodec$CodecException: start failed
                                                                                                    at android.media.MediaCodec.native_start(Native Method)
                                                                                                    at android.media.MediaCodec.start(MediaCodec.java:1885)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:405)
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:800) 
                                                                                                    at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.onInputFormatChanged(MediaCodecVideoTrackRenderer.java:333) 
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:540) 
                                                                                                    at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:523) 
                                                                                                    at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:128) 
                                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:432) 
                                                                                                    at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211) 
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                                    at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by brianwernick** [comment]
It looks like one of the formats is unsupported by the ExoPlayer. If you think this is an ExoMedia issue rather than an ExoPlayer one, please test out the stream in the ExoPlayer demo (If you are using ExoMedia 3.x use ExoPlayer 1.5.x, otherwise the ExoPlayer 2.x will suffice)
Is your videos a Smooth Stream (`.ism`) or an Mpeg Dash (`.mpd`) video? (ExoMedia will capture the last extension `.mpd`)

**Comment by adelumban-sp** [comment]
its na Mpeg Dash

```
String vidURL = "http://level3-cdn.axprod.net/demo/manifestprot.ism/.mpd";

 emVideoView = (EMVideoView) findViewById(R.id.video_view);
 emVideoView.setOnPreparedListener(this);
 emVideoView.setVideoURI(Uri.parse(vidURL));
```

by doing the above code i still get 

```
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
```

**Comment by brianwernick** [comment]
Sorry for taking so long to get to this. Once I started looking in to it I realized the issue is with the `TextureView` backing (default) because it doesn't play well with most DRM settings. If you update the `EMVideoView` to use the surface view backing (`app:useSurfaceViewBacking="true"` in your layout.xml) then it will work.

**Comment by adelumban-sp** [comment]
Thanks @brianwernick  :)
