### ISSUE TITLE
Error:  Unexpected exception loading stream

### ISSUE THREAD

**Issue by yasaman93** [brianwernick/ExoMedia#400]
- ExoMedia version: `4.0.0`
 - Device OS version: `5.0.1`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy Note 4`
 
I test ExoMedia with exoplayer V2 (https://github.com/brianwernick/ExoMedia/tree/dev_v4) and When I want to play audios and videos, I get this error and none of them couldn't play!:

```
02-15 15:44:21.341 12856-13334/com.devbrackets.android.exomediademo E/LoadTask: Unexpected exception loading stream
                                                                                java.lang.IllegalArgumentException: Unexpected char 0x6f4 at 16 in User-Agent value: ExoMedia 4.0.0 (۴۰۰۰۰) / Android 5.0.1 / SM-N910C
                                                                                    at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
                                                                                    at okhttp3.Headers$Builder.add(Headers.java:270)
                                                                                    at okhttp3.Request$Builder.addHeader(Request.java:175)
                                                                                    at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:283)
                                                                                    at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:153)
                                                                                    at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                    at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
                                                                                    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                    at java.lang.Thread.run(Thread.java:818)
02-15 15:44:21.351 12856-13320/com.devbrackets.android.exomediademo E/ExoPlayerImplInternal: Source error.
                                                                                             com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: Unexpected char 0x6f4 at 16 in User-Agent value: ExoMedia 4.0.0 (۴۰۰۰۰) / Android 5.0.1 / SM-N910C
                                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                                              Caused by: java.lang.IllegalArgumentException: Unexpected char 0x6f4 at 16 in User-Agent value: ExoMedia 4.0.0 (۴۰۰۰۰) / Android 5.0.1 / SM-N910C
                                                                                                 at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
                                                                                                 at okhttp3.Headers$Builder.add(Headers.java:270)
                                                                                                 at okhttp3.Request$Builder.addHeader(Request.java:175)
                                                                                                 at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:283)
                                                                                                 at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:153)
                                                                                                 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:623)
                                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                                 at java.lang.Thread.run(Thread.java:818)
```

**Comment by brianwernick** [comment]
Are you running this in the Demo or are you using the `4.0.0-preview1` aar? It looks like the VERSION_CODE wasn't built correctly so you may need to clean the project
