### ISSUE TITLE
Handle the `sending message to a Handler on a dead thread` error.

### ISSUE THREAD

**Issue by droidekas** [brianwernick/ExoMedia#42]
Sometimes I get this stack trace 

```
 Handler (android.os.Handler) {1d54aa83} sending message to a Handler on a dead thread
                                                              java.lang.IllegalStateException: Handler (android.os.Handler) {1d54aa83} sending message to a Handler on a dead thread
                                                                  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                  at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                  at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                  at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                  at android.os.Handler.sendMessage(Handler.java:507)
                                                                  at android.os.Message.sendToTarget(Message.java:416)
                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.setPlayWhenReady(ExoPlayerImplInternal.java:140)
                                                                  at com.google.android.exoplayer.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:145)
                                                                  at com.devbrackets.android.exomedia.exoplayer.EMExoPlayer.setPlayWhenReady(EMExoPlayer.java:255)
                                                                  at com.devbrackets.android.exomedia.EMVideoView.pause(EMVideoView.java:877)
                                                                  at com.devbrackets.android.exomedia.widget.DefaultControls.onPlayPauseClick(DefaultControls.java:508)
                                                                  at com.devbrackets.android.exomedia.widget.DefaultControls$2.onClick(DefaultControls.java:455)
                                                                  at android.view.View.performClick(View.java:4789)
                                                                  at android.view.View$PerformClick.run(View.java:19881)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

Is it possible to catch this issue and restart/reset the player?

**Comment by brianwernick** [comment]
This should only occur when the EMVideoView is being destroyed.  It comes from the base ExoPlayer library and as such, I don't have any control over it being logged.

**Comment by droidekas** [comment]
Ok.Thanks!
