### ISSUE TITLE
Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView

### ISSUE THREAD

**Issue by RomiValladares** [brianwernick/ExoMedia#422]
- I have verified there are no duplicate active or recent bugs, questions, or requests

 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
###### Reproduction Steps
 1.  Add ExoMedia as a dependency (with or without `transitive = true`):
```
    compile ('com.devbrackets.android:exomedia:3.1.1') {
        transitive = true;
    }
```

Complete gradle dependencies:

```
dependencies {
    compile ('com.devbrackets.android:exomedia:3.1.1')

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile('com.crashlytics.sdk.android:crashlytics:2.6.6@aar') {
        transitive = true;
    }
    compile('com.digits.sdk.android:digits:2.0.5@aar') {
        transitive = true;
    }
    compile 'com.google.android.exoplayer:exoplayer:r2.2.0'

    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0'
    compile 'com.annimon:stream:1.1.5'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.github.kevinsawicki:http-request:5.4.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.4.2'
    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'
    compile 'com.google.dagger:dagger:2.8'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.paperdb:paperdb:2.0'
    compile 'com.android.support:support-vector-drawable:24.2.1'
    compile 'com.danikula:videocache:2.6.4'
    compile 'com.google.android.gms:play-services:10.2.1'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.8'

}
```

 2. Create a layout with a `com.devbrackets.android.exomedia.ui.widget.EMVideoView`
 3. Dynamically inflate the layout:

```
    public void createLayout(ViewGroup parent, int visibility) {
        LayoutInflater inflater = (LayoutInflater) getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        layout = (ViewGroup) inflater.inflate(getLayoutRes(), null);
        String tag = createTag();

        if (parent.findViewWithTag(tag) == null) {
            layout.setTag(tag);
            parent.addView(layout, parent.getChildCount());
            layout.setVisibility(visibility);
        }
    }
```

###### Expected Result
The layout inflates correctly and video plays.

###### Actual Result
```
android.view.InflateException: Binary XML file line #25: Binary XML file line #25: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                             at com.discoversdk.buy.feed.view.FullVideoLayout.go(FullVideoLayout.java:31)
                                                                             at com.discoversdk.buy.feed.view.VideoFragment.showFullVideo(VideoFragment.java:142)
                                                                             at com.discoversdk.buy.feed.pager.VideoFeedPagerAdapter.showFullVideoAtIndex(VideoFeedPagerAdapter.java:38)
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.showFullVideo(VideoFeedActivity.java:290)
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.loadCurrentFeed(VideoFeedActivity.java:256)
                                                                             at com.discoversdk.buy.feed.FeedPresenter.lambda$onPageSelected$3(FeedPresenter.java:105)
                                                                             at com.discoversdk.buy.feed.FeedPresenter$$Lambda$4.accept(Unknown Source)
                                                                             at com.annimon.stream.Optional.ifPresent(Optional.java:96)
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onPageSelected(FeedPresenter.java:102)
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onVideoLongPress(FeedPresenter.java:122)
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity$3.onLongPress(VideoFeedActivity.java:221)
                                                                             at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770)
                                                                             at android.view.GestureDetector.-wrap0(GestureDetector.java)
                                                                             at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                             at com.discoversdk.buy.feed.view.FullVideoLayout.go(FullVideoLayout.java:31) 
                                                                             at com.discoversdk.buy.feed.view.VideoFragment.showFullVideo(VideoFragment.java:142) 
                                                                             at com.discoversdk.buy.feed.pager.VideoFeedPagerAdapter.showFullVideoAtIndex(VideoFeedPagerAdapter.java:38) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.showFullVideo(VideoFeedActivity.java:290) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.loadCurrentFeed(VideoFeedActivity.java:256) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.lambda$onPageSelected$3(FeedPresenter.java:105) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter$$Lambda$4.accept(Unknown Source) 
                                                                             at com.annimon.stream.Optional.ifPresent(Optional.java:96) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onPageSelected(FeedPresenter.java:102) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onVideoLongPress(FeedPresenter.java:122) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity$3.onLongPress(VideoFeedActivity.java:221) 
                                                                             at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770) 
                                                                             at android.view.GestureDetector.-wrap0(GestureDetector.java) 
                                                                             at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                             at com.discoversdk.buy.feed.view.FullVideoLayout.go(FullVideoLayout.java:31) 
                                                                             at com.discoversdk.buy.feed.view.VideoFragment.showFullVideo(VideoFragment.java:142) 
                                                                             at com.discoversdk.buy.feed.pager.VideoFeedPagerAdapter.showFullVideoAtIndex(VideoFeedPagerAdapter.java:38) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.showFullVideo(VideoFeedActivity.java:290) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.loadCurrentFeed(VideoFeedActivity.java:256) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.lambda$onPageSelected$3(FeedPresenter.java:105) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter$$Lambda$4.accept(Unknown Source) 
                                                                             at com.annimon.stream.Optional.ifPresent(Optional.java:96) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onPageSelected(FeedPresenter.java:102) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onVideoLongPress(FeedPresenter.java:122) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity$3.onLongPress(VideoFeedActivity.java:221) 
                                                                             at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770) 
                                                                             at android.view.GestureDetector.-wrap0(GestureDetector.java) 
                                                                             at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                             at android.view.ViewStub.inflate(ViewStub.java:259)
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:716)
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:681)
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:668)
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:108)
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                             at com.discoversdk.buy.feed.view.FullVideoLayout.go(FullVideoLayout.java:31) 
                                                                             at com.discoversdk.buy.feed.view.VideoFragment.showFullVideo(VideoFragment.java:142) 
                                                                             at com.discoversdk.buy.feed.pager.VideoFeedPagerAdapter.showFullVideoAtIndex(VideoFeedPagerAdapter.java:38) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.showFullVideo(VideoFeedActivity.java:290) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.loadCurrentFeed(VideoFeedActivity.java:256) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.lambda$onPageSelected$3(FeedPresenter.java:105) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter$$Lambda$4.accept(Unknown Source) 
                                                                             at com.annimon.stream.Optional.ifPresent(Optional.java:96) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onPageSelected(FeedPresenter.java:102) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onVideoLongPress(FeedPresenter.java:122) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity$3.onLongPress(VideoFeedActivity.java:221) 
                                                                             at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770) 
                                                                             at android.view.GestureDetector.-wrap0(GestureDetector.java) 
                                                                             at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                             at android.view.ViewStub.inflate(ViewStub.java:259) 
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:716) 
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:681) 
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:668) 
                                                                             at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:108) 
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                             at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                             at com.discoversdk.buy.feed.view.FullVideoLayout.go(FullVideoLayout.java:31) 
                                                                             at com.discoversdk.buy.feed.view.VideoFragment.showFullVideo(VideoFragment.java:142) 
                                                                             at com.discoversdk.buy.feed.pager.VideoFeedPagerAdapter.showFullVideoAtIndex(VideoFeedPagerAdapter.java:38) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.showFullVideo(VideoFeedActivity.java:290) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity.loadCurrentFeed(VideoFeedActivity.java:256) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.lambda$onPageSelected$3(FeedPresenter.java:105) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter$$Lambda$4.accept(Unknown Source) 
                                                                             at com.annimon.stream.Optional.ifPresent(Optional.java:96) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onPageSelected(FeedPresenter.java:102) 
                                                                             at com.discoversdk.buy.feed.FeedPresenter.onVideoLongPress(FeedPresenter.java:122) 
                                                                             at com.discoversdk.buy.feed.view.VideoFeedActivity$3.onLongPress(VideoFeedActivity.java:221) 
                                                                             at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:770) 
                                                                             at android.view.GestureDetector.-wrap0(GestureDetector.java) 
                                                                             at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5422) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                          Caused by: java.lang.reflect.InvocationTargetException
                                                                             at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                         	at andr
```

**Comment by brianwernick** [comment]
Your problem is that you include both `compile 'com.devbrackets.android:exomedia:3.1.1'` and `compile 'com.google.android.exoplayer:exoplayer:r2.2.0'`; however the 3.x version of ExoMedia depends on ExoPlayer `1.5.x`.
You have 2 options; 
  1. Remove the `compile 'com.google.android.exoplayer:exoplayer:r2.2.0'`
  2. Update to the ExoMedia `4.0.0-preview3` which uses ExoPlayer `2.3.0`

**Comment by RomiValladares** [comment]
Hey Brian, sorry I didn't have the chance to test this. 
Thanks a lot for your response!
