### ISSUE TITLE
Crashing in android studio 2.2.3

### ISSUE THREAD

**Issue by Frankykh** [brianwernick/ExoMedia#440]
When I compile it does well and then I installed on my real device it first load up the video but when it loaded app crashes saying "Unfortunate your app stopped"

**Comment by Frankykh** [comment]
This is not working says ""unfortunately stopped"
My Code is
public class MainActivity extends AppCompatActivity implements OnPreparedListener {
    private VideoView videoView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        setContentView(R.layout.activity_main);
        VideoView videoView = (VideoView) findViewById(R.id.video_view);
        videoView.setOnPreparedListener(this);
        videoView.setVideoURI(Uri.parse("http://stream.jeem.tv/geo/geosuper/playlist.m3u8"));
    }

    @Override
    public void onPrepared() {
        videoView.start();
    }
}
please help me out

**Comment by se-bastiaan** [comment]
Ever heard of Logcat?

**Comment by Frankykh** [comment]
this is the logcat I got
FATAL EXCEPTION: main
                                                                               Process: com.example.hp_pc.myapplication, PID: 2724
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'void com.devbrackets.android.exomedia.ui.widget.VideoView.start()' on a null object reference
                                                                                   at com.example.hp_pc.myapplication.MainActivity.onPrepared(MainActivity.java:26)
                                                                                   at com.devbrackets.android.exomedia.core.ListenerMux.performPreparedHandlerNotification(ListenerMux.java:286)
                                                                                   at com.devbrackets.android.exomedia.core.ListenerMux.access$000(ListenerMux.java:45)
                                                                                   at com.devbrackets.android.exomedia.core.ListenerMux$1.run(ListenerMux.java:277)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by se-bastiaan** [comment]
You're doing `VideoView videoView = (VideoView) findViewById(R.id.video_view);` in `onCreate` and then you want to access that VideoView in `onPrepared`, but it is `null` since the scope isn't correct. I'm assuming you have an instance variable that is called `videoView` so you should do `videoView = (VideoView) findViewById(R.id.video_view);` instead. You should do some research to learn the difference between instance variables, class variables and local variables.

**Comment by Frankykh** [comment]
Thanks for your quick reply...

**Comment by Frankykh** [comment]
But still the vidro is not loaded....
