### ISSUE TITLE
File Not Found when reading from Internal Storage

### ISSUE THREAD

**Issue by AnthonyKoueik** [brianwernick/ExoMedia#441]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Actual Result
```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/data/mobi.foo.sanctamaria/files/Dream English Traditional ABC01.mp3: open failed: ENOENT (No such file or directory)
                                                                                 at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                                                                                 at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                                                                                 at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                 at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                 at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                              Caused by: com.google.android.exoplayer.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/data/mobi.foo.sanctamaria/files/Dream English Traditional ABC01.mp3: open failed: ENOENT (No such file or directory)
                                                                                 at com.google.android.exoplayer.upstream.FileDataSource.open(FileDataSource.java:75)
                                                                                 at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                                                                                 at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                              Caused by: java.io.FileNotFoundException: /data/data/mobi.foo.sanctamaria/files/Dream English Traditional ABC01.mp3: open failed: ENOENT (No such file or directory)
                                                                                 at libcore.io.IoBridge.open(IoBridge.java:456)
                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
                                                                                 at com.google.android.exoplayer.upstream.FileDataSource.open(FileDataSource.java:67)
                                                                                 at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135) 
                                                                                 at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720) 
                                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                                              Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                 at libcore.io.Posix.open(Native Method)
                                                                                 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                 at libcore.io.IoBridge.open(IoBridge.java:442)
                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117) 
                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149) 
                                                                                 at com.google.android.exoplayer.upstream.FileDataSource.open(FileDataSource.java:67) 
                                                                                 at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135) 
                                                                                 at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720) 
                                                                                 at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                 at java.lang.Thread.run(Thread.java:818) 
05-01 00:29:57.651 10900-10900/mobi.foo.sanctamaria E/EMPlaylistService: MediaPlayer Error: what=0, extra=0
```

**Comment by brianwernick** [comment]
Does that file actually exist and is it readable?

**Comment by AnthonyKoueik** [comment]
Hi, yes i can play it with the Android media MediaPlayer

**Comment by AnthonyKoueik** [comment]
`com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/user/0/com.devbrackets.android.exomediademo/files/Dream English Traditional ABC01.mp3: open failed: ENOENT (No such file or directory)
                                                                                                 at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:70)
                                                                                                 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                 at java.lang.Thread.run(Thread.java:761)
                                                                                              Caused by: java.io.FileNotFoundException: /data/user/0/com.devbrackets.android.exomediademo/files/Dream English Traditional ABC01.mp3: open failed: ENOENT (No such file or directory)
                                                                                                 at libcore.io.IoBridge.open(IoBridge.java:455)
                                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247)
                                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128)
                                                                                                 at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:62)
                                                                                                 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                                 at java.lang.Thread.run(Thread.java:761) 
                                                                                              Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                 at libcore.io.Posix.open(Native Method)
                                                                                                 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:187)
                                                                                                 at libcore.io.IoBridge.open(IoBridge.java:441)
                                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:247) 
                                                                                                 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:128) 
                                                                                                 at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:62) 
                                                                                                 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                                                 at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                                                 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                                 at java.lang.Thread.run(Thread.java:761) `

**Comment by AnthonyKoueik** [comment]
both com.google.android.exoplayer and com.google.android.exoplayer2 have same issue :(

**Comment by AnthonyKoueik** [comment]
Hi, do you have any solution please ?

**Comment by brianwernick** [comment]
I've tested the Demo app and it doesn't have any issues playing local files meaning that the issue is on your end.

**Comment by AnthonyKoueik** [comment]
Hello Brian  please can you tell me how to read from Internal Storage ? (not sd card)
my mp3 file is stored in the Private Internal Storage?
I tried it on the demo and same issue .

**Comment by brianwernick** [comment]
How are you passing in the Uri? Are you handling the spaces in your path?

**Comment by AnthonyKoueik** [comment]
No...
should i do it like this,  Uri.parse(path) ?

**Comment by brianwernick** [comment]
Yeah, `Uri.parse(filePath)` should handle whitespaces

**Comment by AnthonyKoueik** [comment]
much thanks, it worked , i feel so noob lol
