### ISSUE TITLE
conflict Audience Network and ExoPlayer

### ISSUE THREAD

**Issue by hoangnguyen15** [brianwernick/ExoMedia#455]
How do I fix it, please ?
if I remove  " compile 'com.facebook.android:audience-network-sdk:4.+'" is working well. but when more then my project  error messages.

Gradle:
> dependencies {
    compile 'com.android.support:recyclerview-v7:25.0.0'
    compile 'com.android.support:cardview-v7:25.0.0'
    compile 'com.android.support:palette-v7:25.0.0'
    compile 'com.android.support:design:25.0.0'
    compile 'com.squareup.picasso:picasso:2.4.0'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.devbrackets.android:exomedia:3.1.1'
    compile files('libs/universal-image-loader-1.6.3-with-src.jar')
    compile project(':vitamio')
    compile 'com.google.android.gms:play-services-ads:7.5.0'
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'org.jsoup:jsoup:1.9.2'
    compile 'com.devbrackets.android:exomedia:4.0.1'
    compile 'com.facebook.android:audience-network-sdk:4.+'
}

error 

> 05-17 23:23:15.686 13784-14031/com.teamdev.xemtruyenhinh E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
05-17 23:23:15.746 13784-14031/com.teamdev.xemtruyenhinh E/chromium: [ERROR:gl_surface_egl.cc(264)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE
05-17 23:23:18.138 13784-13784/com.teamdev.xemtruyenhinh E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.teamdev.xemtruyenhinh, PID: 13784
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.teamdev.xemtruyenhinh/com.teamdev.xemtruyenhinh.PlayerExoActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2348)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5345)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
                                                                            Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class com.devbrackets.android.exomedia.ui.widget.EMVideoView
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380)
                                                                               at android.app.Activity.setContentView(Activity.java:2154)
                                                                               at com.teamdev.xemtruyenhinh.PlayerExoActivity.onCreate(PlayerExoActivity.java:49)
                                                                               at android.app.Activity.performCreate(Activity.java:6012)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5345) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                               at android.app.Activity.setContentView(Activity.java:2154) 
                                                                               at com.teamdev.xemtruyenhinh.PlayerExoActivity.onCreate(PlayerExoActivity.java:49) 
                                                                               at android.app.Activity.performCreate(Activity.java:6012) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5345) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 
                                                                            Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                               at android.view.ViewStub.inflate(ViewStub.java:264)
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:716)
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:681)
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:668)
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:108)
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                               at android.app.Activity.setContentView(Activity.java:2154) 
                                                                               at com.teamdev.xemtruyenhinh.PlayerExoActivity.onCreate(PlayerExoActivity.java:49) 
                                                                               at android.app.Activity.performCreate(Activity.java:6012) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5345) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.ViewStub.inflate(ViewStub.java:264) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:716) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:681) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:668) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:108) 
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                               at android.app.Activity.setContentView(Activity.java:2154) 
                                                                               at com.teamdev.xemtruyenhinh.PlayerExoActivity.onCreate(PlayerExoActivity.java:49) 
                                                                               at android.app.Activity.performCreate(Activity.java:6012) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5345) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 
                                                                            Caused by: java.lang.NoClassDefFoundError: com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate
                                                                               at com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView.setup(ExoTextureVideoView.java:183)
                                                                               at com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView.<init>(ExoTextureVideoView.java:56)
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.ViewStub.inflate(ViewStub.java:264) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.inflateVideoView(EMVideoView.java:716) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.initView(EMVideoView.java:681) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.setup(EMVideoView.java:668) 
                                                                               at com.devbrackets.android.exomedia.ui.widget.EMVideoView.<init>(EMVideoView.java:108) 
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                               at android.app.Activity.setContentView(Activity.java:2154) 
                                                                               at com.teamdev.xemtruyenhinh.PlayerExoActivity.onCreate(PlayerExoActivity.java:49) 
                                                                               at android.app.Activity.performCreate(Activity.java:6012) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:135) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5345) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by brianwernick** [comment]
You're including 2 different versions of ExoMedia.

**Comment by hoangnguyen15** [comment]
No.  1 versions of ExoMedia , if I remove " compile 'com.facebook.android:audience-network-sdk:4.+'" is working well. but when more " compile 'com.facebook.android:audience-network-sdk:4.+'" then my project error messages.

**Comment by brianwernick** [comment]
You have both `compile 'com.devbrackets.android:exomedia:3.1.1'` and `compile 'com.devbrackets.android:exomedia:4.0.1'` in the dependencies you listed. My assumption is that audience is relying on either ExoPlayer 1.5.x or ExoPlayer 2.x

**Comment by hoangnguyen15** [comment]
sorry.I still get the same error as above with exoplayer 3.1.1

**Comment by brianwernick** [comment]
This is an issue with the audience network library as they are behind on the ExoPlayer version (`2.0.3` whereas ExoMedia `4.0.1` uses `2.4.0`)
The dependency tree for audience
```
+--- com.facebook.android:audience-network-sdk:4.+ -> 4.22.1
|    +--- com.android.support:appcompat-v7:25.0.0 -> 25.3.1 (*)
|    +--- com.android.support:recyclerview-v7:25.0.0 -> 25.0.1 (*)
|    +--- com.android.support:support-annotations:25.0.0 -> 25.3.1
|    +--- com.android.support:support-v4:25.0.0 -> 25.3.1 (*)
|    +--- com.google.android.exoplayer:exoplayer:r2.0.3
|    |    \--- com.android.support:support-annotations:24.2.0 -> 25.3.1
|    \--- com.google.android.gms:play-services-ads:8.4.0
|         \--- com.google.android.gms:play-services-basement:8.4.0
|              \--- com.android.support:support-v4:23.0.0 -> 25.3.1 (*)
```

**Comment by timeline263** [comment]
There is a way you can try
....
compile ('com.facebook.android:audience-network-sdk:4.24.0') {
        exclude group: 'com.google.android.exoplayer'
    }

**Comment by banxxi** [comment]
@timeline263 you hit it :D 👍

**Comment by ClaudeHangui** [comment]
@banxxi....Indeed he it !!...I was excluding..This is what I was instead doing:                                              `        exclude group: 'com.google.android.exoplayer', module: 'exoplayer-r2.0.3'
`  and of course it didn't work...Excluding it as a group did the trick
