### ISSUE TITLE
Error in EMAudioPlayer (Fix SmoothStream support)

### ISSUE THREAD

**Issue by ahpiau18** [brianwernick/ExoMedia#47]
Hi, I'm having issue while try to stream on a URL

        Uri uri = Uri.parse("http://shout01.stream.hostworks.com.au/3aw");
        EMAudioPlayer player = new EMAudioPlayer(this);
        player.setDataSource(this, uri, MediaUtil.MediaType.SMOOTH_STREAM);
        player.prepareAsync();

        player.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
            @Override
            public void onPrepared(MediaPlayer mp) {
                mp.start();
            }
        });

Error:

12-23 23:54:46.577 25725-25756/? E/ExoPlayerImplInternal: Internal track renderer error.
                                                          com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://shout01.stream.hostworks.com.au/3aw
at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
    Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: 
    Unable to connect to http://shout01.stream.hostworks.com.au/3aw
at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733)
at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
    Caused by: java.net.ProtocolException: Unexpected status line: ICY 200 OK
at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:191)
at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136) 
at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733) 
at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:841)

**Comment by brianwernick** [comment]
It looks like I completely missed adding Smooth Stream support in the extractors. :(  I'll look in to it, if it's pretty quick I might create an updated release with it

**Comment by brianwernick** [comment]
It looks like SmoothStream support will take a while so it will probably be added after this week.

**Comment by ahpiau18** [comment]
Thanks :)

**Comment by ahpiau18** [comment]
i found it work when i use the code as below

        Uri uri = Uri.parse("http://shout01.stream.hostworks.com.au/3aw");
        EMAudioPlayer player = new EMAudioPlayer(getContext());
        player.setDataSource(getContext(), uri, MediaUtil.MediaType.AAC);
        player.prepareAsync();
        player.start();

//        player.reset();
//
//        player.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
//            @Override
//            public void onPrepared(MediaPlayer mp) {
//                mp.start();
//            }
//        });

Merry Chritmas :)

**Comment by brianwernick** [comment]
Smooth Stream support has been added with the help of @se-bastiaan and will be in the next release (it's looking like a 2.5.0)
