### ISSUE TITLE
OnError not catching out of memory ExoPlayer Errors

### ISSUE THREAD

**Issue by parkgrrr** [brianwernick/ExoMedia#474]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Custom`
 - Device Name: `Allwinner Quad-Core R18 Ads`
 
###### Reproduction Steps
Difficult to produce, but occasionally happens when playing an adaptive stream.

###### Expected Result
onError callback should fire, and my code should handle it
###### Actual Result
 I see an out of memory exoPlayer error.  I normally have a dialog that catches all errors from the onError callback, but it's not firing.

**Comment by brianwernick** [comment]
A stacktrace would be nice

**Comment by parkgrrr** [comment]
Sorry about that, I meant to paste it before I hit submit.  On second glance it is actually coming from java.lang.outOfMemoryError which isn't triggered by exoplayer.
````06-08 05:23:47.971 28634-4332/com.flexline W/art: Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 59376 free bytes and 57KB until OOM"
06-08 05:23:48.409 28634-4332/com.flexline W/art: Throwing OutOfMemoryError "Failed to allocate a 65548 byte allocation with 3872 free bytes and 3KB until OOM"
06-08 05:23:48.496 28634-4332/com.flexline E/LoadTask: Unexpected error loading stream
                                                       java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 3872 free bytes and 3KB until OOM
                                                           at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
                                                           at com.google.android.exoplayer2.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:572)
                                                           at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:507)
                                                           at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
                                                           at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
                                                           at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:287)
                                                           at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:264)
                                                           at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:200)
                                                           at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                           at java.lang.Thread.run(Thread.java:818)
06-08 05:23:48.576 28634-4275/com.flexline E/drive: Top level exception encountered
                                                    java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 3872 free bytes and 3KB until OOM
                                                        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
                                                        at com.google.android.exoplayer2.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:572)
                                                        at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:507)
                                                        at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
                                                        at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
                                                        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:287)
                                                        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:264)
                                                        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:200)
                                                        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                        at java.lang.Thread.run(Thread.java:818)
06-08 05:23:48.640 28634-4332/com.flexline E/drive: Top level exception encountered
                                                    java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 3872 free bytes and 3KB until OOM
                                                        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
                                                        at com.google.android.exoplayer2.extractor.DefaultTrackOutput.prepareForAppend(DefaultTrackOutput.java:572)
                                                        at com.google.android.exoplayer2.extractor.DefaultTrackOutput.sampleData(DefaultTrackOutput.java:507)
                                                        at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
                                                        at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
                                                        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:287)
                                                        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:264)
                                                        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:200)
                                                        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                        at java.lang.Thread.run(Thread.java:818)
 
````
