### ISSUE TITLE
Live Stream Rendering error

### ISSUE THREAD

**Issue by Norhan-El-Ashry** [brianwernick/ExoMedia#496]
Hii

When I tried to play .ts live streams e.x.

http://avatar-iptv.net:1795/live/az5130/PPYnz6ewcVb1/213.ts

It works in some devices but with no audio track

in other devices it gives me that error

`com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.sprd.mp3.decoder, Format(1/257, null, audio/mpeg-L2, -1, null, [-1, -1, -1.0], [2, 48000])

com.google.android.exoplayer2.ExoPlaybackException
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:380)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:367)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:796)
at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:219)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:494)
at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.sprd.mp3.decoder, Format(1/257, null, audio/mpeg-L2, -1, null, [-1, -1, -1.0], [2, 48000])
... 9 more
Caused by: java.lang.IllegalStateException
at android.media.MediaCodec.native_configure(Native Method)
at android.media.MediaCodec.configure(MediaCodec.java:262)
at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.configureCodec(MediaCodecAudioRenderer.java:201)
at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:356)
... 8 more`

I guess that there is a problem with audio track. Is there a way to fix it or download an alternative track?
and how can I get the track and merge it with video.

Thank you

**Comment by brianwernick** [comment]
This isn't an issue with ExoMedia, rather the ExoPlayer backing. Please open an issue in their tracker instead.

**Comment by Norhan-El-Ashry** [comment]
I opened an issue in ExoPlayer tracker and It was recommended to  use the
ffmpeg extension in my project. because  mpeg-L2 is not part of the CDD

i found the following code in ExoMedia.java  but I couldn't go further. How
can I use ffmpeg.FfmpegAudioRenderer to decode the audio file then switch back
to default  when playing other streams

List<String> audioClasses = registeredRendererClasses.get(RendererType.AUDIO
);

audioClasses.add("com.google.android.exoplayer2.ext.opus.LibopusAudioRenderer");
audioClasses.add("com.google.android.exoplayer2.ext.flac.LibflacAudioRenderer");
audioClasses.add("com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioRenderer");

**Comment by brianwernick** [comment]
The `MediaCodecAudioRenderer` is used by default, which means that as long as it supports the format being played it will be used in place of the ffmpeg renderer. That means that all you need to do for it to work is include the ffmpeg exoplayer extension library in your dependencies.
