### ISSUE TITLE
Exomedia Video View won't inflate when Exoplayer 2.5.1 is also included as a dependancy

### ISSUE THREAD

**Issue by parkgrrr** [brianwernick/ExoMedia#509]
This is probably due to Exomedia using an older Exoplayer version, and this also may not be a common scenario, so I understand if it's not supported.

- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Allwinner`
 - Device Name: `Custom`
 
###### Reproduction Steps
 1.  Add exoplayer r2.5.1 as dependancy
2. Add exomedia 4.0.3 as a dependancy

###### Expected Result
Previously, both libraries could be used side by side
###### Actual Result
I get the following error when loading an activity

```
08-30 12:40:18.498 17768-17768/com.flexline E/drive: Top level exception encountered
                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.flexline/com.flexline.workout.WorkoutActivity}: android.view.InflateException: Binary XML file line #114: Binary XML file line #14: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:148)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
                                                      Caused by: android.view.InflateException: Binary XML file line #114: Binary XML file line #14: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                         at com.flexline.workout.WorkoutDescriptionFragment.onCreateView(WorkoutDescriptionFragment.java:67)
                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                         at android.app.Activity.performStart(Activity.java:6268)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                         at android.os.Looper.loop(Looper.java:148) 
                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742) 
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632) 
                                                      Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                         at com.flexline.workout.WorkoutDescriptionFragment.onCreateView(WorkoutDescriptionFragment.java:67) 
                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248) 
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340) 
                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569) 
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636) 
                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415) 
                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201) 
                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155) 
                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064) 
                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379) 
                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
                                                         at android.app.Activity.performStart(Activity.java:6268) 
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                         at android.os.Looper.loop(Looper.java:148) 
                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742) 
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632) 
                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                         at java.lang.reflect.Constructor.newInstance(Native Method)
                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                         at com.flexline.workout.WorkoutDescriptionFragment.onCreateView(WorkoutDescriptionFragment.java:67) 
                                                         at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248) 
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340) 
                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569) 
                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636) 
                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758) 
                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415) 
                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201) 
                                                         at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155) 
                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064) 
                                                         at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379) 
                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
                                                         at android.app.Activity.performStart(Activity.java:6268) 
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                         at android.os.Looper.loop(Looper.java:148) 
                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742) 
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632) 
                                                      Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                         at android.view.ViewStub.inflate(ViewStub.java:259)
                                                     	at com.devbrackets.android.exomedia.ui.widget.VideoView.inflateVideoView(Vi
```

**Comment by brianwernick** [comment]
See #500. The reason it won't inflate is because google made an additive interface change between 2.4 and 2.5 which causes an implementation to be incomplete. I've updated master with the 2.5.0 release and am hoping to have time soon to focus on an ExoMedia 4.1 release which will include the exoplayer 2.5
