### ISSUE TITLE
Unable to create DrmSessionManager error

### ISSUE THREAD

**Issue by ominfowave** [brianwernick/ExoMedia#510]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

 - ExoMedia version: `4.0.3`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Redmi`
 - Device Name: `Note 3`
 
###### Reproduction Steps
 0.  Normal setup and set server file url

###### Actual Result
ExoMediaPlayer: Unable to create a DrmSessionManager due to an exception
                                                                   com.google.android.exoplayer2.drm.UnsupportedDrmException: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
                                                                       at com.google.android.exoplayer2.drm.FrameworkMediaDrm.newInstance(FrameworkMediaDrm.java:51)
                                                                       at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.generateDrmSessionManager(ExoMediaPlayer.java:553)
                                                                       at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.<init>(ExoMediaPlayer.java:153)
                                                                       at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.initExoPlayer(ExoVideoDelegate.java:212)
                                                                       at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setup(ExoVideoDelegate.java:208)
                                                                       at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.<init>(ExoVideoDelegate.java:56)
                                                                       at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.setup(ExoSurfaceVideoView.java:176)
                                                                       at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.<init>(ExoSurfaceVideoView.java:54)
                                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                       at android.view.ViewStub.inflate(ViewStub.java:259)
                                                                       at com.devbrackets.android.exomedia.ui.widget.VideoView.inflateVideoView(VideoView.java:737)
                                                                       at com.devbrackets.android.exomedia.ui.widget.VideoView.initView(VideoView.java:694)
                                                                       at com.devbrackets.android.exomedia.ui.widget.VideoView.setup(VideoView.java:681)
                                                                       at com.devbrackets.android.exomedia.ui.widget.VideoView.<init>(VideoView.java:108)
                                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                       at module.adapter.FeedAdapter.onCreateViewHolder(FeedAdapter.java:60)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)
                                                                       at android.view.View.measure(View.java:16497)
                                                                       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                       at android.view.View.measure(View.java:16497)
                                                                       at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                       at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
                                                                       at android.view.View.measure(View.java:16497)
                                                                       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)

**Comment by brianwernick** [comment]
This is an ExoPlayer question and doesn't depend on the passthroughs that ExoMedia provides. As long as you are using the SurfaceView (default) backing then you should post a question there.

**Comment by ominfowave** [comment]
Ok thanks for your response, i didn't know that.
