### ISSUE TITLE
InflateException after updating SDK repository to latest version.

### ISSUE THREAD

**Issue by ominfowave** [brianwernick/ExoMedia#518]
I am getting InflateException from today after updating SDK, it is working fine if i build the app in other system with not updated SDK.

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

Device 1:
 - ExoMedia version: `4.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Xiaomi Redmi`
 - Device Name: `Note 3`
Device 2:
 - ExoMedia version: `4.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Lenovo`
 - Device Name: `K5 Note`

 
###### Reproduction Steps
 0. Update SDK to latest version
 1. Build new apk
 2. Run app  

###### Expected Result
 Basic video playing
###### Actual Result
Error: 
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.dzlyoum.android, PID: 11482
                                                                     android.view.InflateException: Binary XML file line #116: Binary XML file line #116: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                         at module.adapter.FeedAdapter.onCreateViewHolder(FeedAdapter.java:56)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5836)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5060)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4970)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
                                                                         at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2843)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                         at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                         at android.view.View.measure(View.java:18811)
                                                                         at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
                                                                         at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                                                                         at android.os.Handler.handleCallback(Handler.java:742)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                     	at andr

**Comment by ominfowave** [comment]
Sorry for adding this issue, it solved after updating ExoMedia library to latest version.
