### ISSUE TITLE
Subtitles exo.setTrack ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#525]
Hey Brian,

When i'm trying to add the CLOSED_CAPTION track i'm getting 

```
Internal runtime error.
java.lang.ArrayIndexOutOfBoundsException: length=1; index=3
                                                                                        at com.google.android.exoplayer2.source.TrackGroupArray.get(TrackGroupArray.java:56)
                                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector$SelectionOverride.createTrackSelection(MappingTrackSelector.java:67)
                                                                                        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:310)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.selectTracks(ExoPlayerImplInternal.java:1505)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:767)
                                                                                        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
```

I saw that you are working on it and maybe it will be on the next release. 
Any idea when this will be out?

Thank you!!

**Comment by brianwernick** [comment]
See https://github.com/brianwernick/ExoMedia/pull/498 and #115
