### ISSUE TITLE
Source error.

### ISSUE THREAD

**Issue by PiYun01** [brianwernick/ExoMedia#536]
String path 
   =/storage/emulated/0/Android/data/com.bloomlife.luobo/files/Podcasts/1511944471882.amr ;
 
mPlayer.setDataSource(Uri.parse("file://" + path));

 

Source error.
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
                                                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
                                                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by brianwernick** [comment]
`.amr` is not a supported media format
