### ISSUE TITLE
while playing a streaming link getting a Toast "null"

### ISSUE THREAD

**Issue by sajjad0321** [brianwernick/ExoMedia#552]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `7.1.1`
 - Devide Manufacturer: `Samsung`
 - Device Name: `C9 Pro`
 
01-14 12:37:38.393 12419-14611/com.muparse E/ExoPlayerImplInternal: Source error.
                                                                    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 406
                                                                        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:141)
                                                                        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:702)
                                                                        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:762)

**Comment by brianwernick** [comment]
Without more information it jus looks like you are passing a badly formatted media url. And the library itself doesn't show any toast notifications

**Comment by sajjad0321** [comment]
I have M3U list in it some r playing some r not.

**Comment by sajjad0321** [comment]
which kind of info do i provide ?

**Comment by brianwernick** [comment]
Are you seeing this in the demo app? what Url's are you using? have you verified this is coming from ExoMedia and not some part of your code?

**Comment by sajjad0321** [comment]
yes its comming in Exomedia.setOnErrorListener
