### ISSUE TITLE
NullPointerException on Creating ExoAudioPlayer

### ISSUE THREAD

**Issue by syedalinaqi** [brianwernick/ExoMedia#554]
- [-] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `5.1.1`
 
###### Reproduction Steps
 0.  Created a Global ExoAudioPlayer
 1.  Initialized it on Activity onCreate
 2.  Set an Internal Path on Fab Click using  `player.setDataSource(Uri.parse(path));`

###### Expected Result
Expected to see the App Run
###### Actual Result
App Crashed on Activity Create with CrashLog

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.devbrackets.android.exomedia.core.ListenerMux.onBufferingUpdate(int)' on a null object reference
                                                                              at com.devbrackets.android.exomedia.core.audio.ExoAudioPlayer$InternalListeners.onBufferingUpdate(ExoAudioPlayer.java:243)
                                                                              at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer$BufferRepeatListener.onRepeat(ExoMediaPlayer.java:644)
                                                                              at com.devbrackets.android.exomedia.util.Repeater$PollRunnable.run(Repeater.java:137)
                                                                              at android.os.Handler.handleCallback(Handler.java:810)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:189)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)`

**Comment by brianwernick** [comment]
Please post your creation and any relevant code

**Comment by brianwernick** [comment]
Oh, I just realized you are referencing the `ExoAudioPlayer`. You shouldn't use that directly, instead use the `AudioPlayer`

**Comment by syedalinaqi** [comment]
Ok. Thanks. will try it and get back to u..
