### ISSUE TITLE
Getting exception when using aar file in Android

### ISSUE THREAD

**Issue by keshav1139** [brianwernick/ExoMedia#557]
###### Include the following:
 - ExoMedia version: 4.1.0
 - Device OS version: `All versions`
 - Devide Manufacturer: `All phones`
 - Device Name: `All Phones`
 
###### Reproduction Steps
1. I have added initially Exo Media as a module 
2. I have customized it and I have created an aar
3. I have added that aar to libs and have referenced the same in gradle file
4. When I run my app now, i am getting the following exception

###### Expected Result
Exomedia should work as expected

###### Actual Result
Crashes by producing the following exception
```
FATAL EXCEPTION: main Process: com.dabkick.videosdk, PID: 12962
android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
 Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at android.view.LayoutInflater.createView(LayoutInflater.java:645)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
at com.dabkick.videosdk.livesession.stage.VideoManager$VideoItem.<init>(VideoManager.java:196)
at com.dabkick.videosdk.livesession.stage.VideoManager.add(VideoManager.java:48)
at com.dabkick.videosdk.livesession.stage.StageDatabase$2.onChildAdded(StageDatabase.java:132)
  at com.google.android.gms.internal.zzdri.zza(Unknown Source)
  at com.google.android.gms.internal.zzdwu.zzbvb(Unknown Source)
  at com.google.android.gms.internal.zzdxa.run(Unknown Source)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:159)
  at android.app.ActivityThread.main(ActivityThread.java:6139)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView
  Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView
 Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
    at android.view.LayoutInflater.createView(LayoutInflater.java:645)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
    at android.view.ViewStub.inflate(ViewStub.java:259)
    at com.devbrackets.android.exomedia.ui.widget.VideoView.inflateVideoView(VideoView.java:772)
  at com.devbrackets.android.exomedia.ui.widget.VideoView.initView(VideoView.java:729)
at com.devbrackets.android.exomedia.ui.widget.VideoView.setup(VideoView.java:716)
 at com.devbrackets.android.exomedia.ui.widget.VideoView.<init>(VideoView.java:109)
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
   at android.view.LayoutInflater.createView(LayoutInflater.java:645)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
   at com.dabkick.videosdk.livesession.stage.VideoManager$VideoItem.<init>(VideoManager.java:196)
 at com.dabkick.videosdk.livesession.stage.VideoManager.add(VideoManager.java:48)
at com.dabkick.videosdk.livesession.stage.StageDatabase$2.onChildAdded(StageDatabase.java:132)
 at com.google.android.gms.internal.zzdri.zza(Unknown Source)
01-18 12:14:41.665 12962-12962/com.dabkick.videosdk E/AndroidRuntime:     at com.google.android.gms.internal.zzdwu.zzbvb(Unknown Source)
 at com.google.android.gms.internal.zzdxa.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:159)
 at android.app.ActivityThread.main(ActivityThread.java:6139)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
   Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer;
 at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.initExoPlayer(ExoVideoDelegate.java:212)
at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setup(ExoVideoDelegate.java:208)
at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.<init>(ExoVideoDelegate.java:56)
at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.setup(ExoSurfaceVideoView.java:176)
 at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.<init>(ExoSurfaceVideoView.java:54)
  	... 33 more
 Caused by: java.lang.ClassNotFoundException: com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer
    at java.lang.VMClassLoader.findLoadedClass(Native Method)
    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 38 more
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$DefaultEventListener;
  	... 38 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$DefaultEventListener" on path: DexPathList[[zip file "/data/app/com.dabkick.videosdk-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dabkick.videosdk-1/lib/arm64, /data/app/com.dabkick.videosdk-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```
It works fine in the branch where the library is used as module, exception occurs only when aar file is generated and used in another branch.

**Comment by brianwernick** [comment]
It looks like the `aar` your are exporting doesn't include the correct maven information to point to the dependencies of ExoMedia itself or you aren't using the transitive maven property. This is why you are getting a `ClassNotFoundException` for `DefaultEventListener` which is an ExoPlayer component. You'll need to either fix the pom file that is exported with the aar in your build or manually add the transitive dependencies (if the pom is the issue), or you need to tell gradle that you want the transitive dependencies as well as the aar (e.g. `compile ("com.devbrackets.android:exomedia:4.1.0@aar") { transitive = true }`) or just drop the `@aar` specifier

**Comment by keshav1139** [comment]
Hi @brianwernick  I tried adding 
```
{ transitive = true }
```
But that did not solve my problem. My Compile time dependency line looks as shown below:
```
compile(name: 'StageVideoView', ext: 'aar') {
        transitive = true
    }
```
StageVideoView is the exo media module name(renamed to StageVideoView). We have changed the UI of the exo media by changing the layout files, now we need to integrate this in our project and we have a limitation we cannot use this as a sub project so I have generated aar file of customized library, Now I am trying to use that aar file as dependency.

**Comment by brianwernick** [comment]
You are probably deploying the artifact incorrectly or aren't including the necessary pom.xml, etc. files that are necessary for maven to work correctly (via gradles `compile`). So you need to fix your deployment to the maven repository if you are deploying it, add a correct pom file to the directory you have the aar file, or manually include the transitive dependencies that `StageVideoView` depends on (these would be everything in the ExoMedia [dependencies](https://github.com/brianwernick/ExoMedia/blob/master/library/build.gradle#L13) block)
