### ISSUE TITLE
MediaSourceProvider comparison bug

### ISSUE THREAD

**Issue by enginegl** [brianwernick/ExoMedia#560]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `8.1`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel`
 
###### Reproduction Steps
 0. Clone ExoMedia repo
 1. Add WRITE_EXTERNAL_STORAGE permission
 2. Add new sample to _videoSamples_ as follows:
`videoSamples.add(new Sample("Local media", Environment.getExternalStorageDirectory().getAbsolutePath() + "/test.mp4"));`
 3.  Upload any mp4 video to your phone
 4. Rename it to test.mp4
 5. Run demo app and check that everything is OK
 6. Rename test.mp4 to m3u8test.mp4
 7. Update _videoSamples_ Sample path
 8. Run demo app and try to play _Local media_

###### Expected Result

Video playback starts normally

###### Actual Result

`ExoPlayerImplInternal: Source error.
                                                          com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
                                                              at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:131)
                                                              at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:47)
                                                              at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:126)
                                                              at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                              at java.lang.Thread.run(Thread.java:764)`

**Comment by brianwernick** [comment]
It looks like we aren't correctly escaping the `.` in the regex matching criteria for hls, dash, and smooth stream in [`ExoMedia.Data`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L147). Nice catch

**Comment by brianwernick** [comment]
For reference this was changed in #14 so we need to make sure those types of urls are handled correctly as well

**Comment by enginegl** [comment]
I added the following line as a temporary solution for my case:
```
protected static SourceTypeBuilder findByLooseComparison(@NonNull Uri uri) {
        try {
            if (new File(uri.getPath()).exists()) return null;
        } catch (Exception e) {
            e.printStackTrace();
        }
        for (SourceTypeBuilder sourceTypeBuilder : ExoMedia.Data.sourceTypeBuilders) {
            if (sourceTypeBuilder.looseComparisonRegex != null && uri.toString().matches(sourceTypeBuilder.looseComparisonRegex)) {
                return sourceTypeBuilder;
            }
        }

        return null;
    }
```

But I think it could be done with extra checks (like is uri's path starts from / or file:// or web scheme).
I'll be glad to see more beautiful solution.

**Comment by enginegl** [comment]
I think that 'm3u8' in URLs like http://pl.youku.com/playlist/m3u8?vid=XMTI5MjIxODIwOA%2525253D%2525253D&keyframe=1&ev=1&ts=1441603988&type=hd2&ep=cSaQG0%2525252BNVccI7SLaiT8bNiWzdnAOXJZ3kmaA%2525252FIgbSMRQMa%2525252FA6DPcqJqwS%2525252Fg%2525253D&token=7057&oip=2021932405&ctype=12&sid=344160398815112a9a271 from #14 doesn't mean anything.

It could lead us to any file.
'm3u8' could be a part of video id / token for mp4 or something else.

**Comment by brianwernick** [comment]
In general I agree that it doesn't really mean much, however if there's an easy way to support it (e.g. look for `m3u8` as the last portion of the url excluding variables) then we should. But with the addition of overriding the builders in `4.0` I don't think it's a super high priority if it complicates finding correct matching builders.

**Comment by nabil6391** [comment]
Hi, Thanks for the great library.... A similar problem occured for me as well. For me the url:
"https://media.blubrry.com/muslim_central_quran/p/audio1.qurancentral.com/mufti-menk/mufti-ismail-menk-muslimcentral.com-end-of-surah-furqaan-2018-01-23-03-34-15.mp3" 

caused the MediaSourceProvider to consider this as a SsMediaSourceBuilder. 

This is due to the *.ism.* regex comparison mistake with "-ismail-" in the url. 

Looking forward to a fix for this. :)
