### ISSUE TITLE
URL not working - 400 Bad Request Error

### ISSUE THREAD

**Issue by asimbashir** [brianwernick/ExoMedia#561]
I'm trying to open SharePoint videos using its REST APIs. Below is a valid URL to a video content on SharePoint but it is giving us 400 bad request error
`https://TENANT-URL/sites/retail/RETAIL/_api/web/GetFileByServerRelativeUrl('/sites/retail/retail/Video Trainings/A Caregiver''s Journey/A Caregiver''s Journey.mp4')/$value`

I have using encoding the URL but it is not working either.

@brianwernick

**Comment by brianwernick** [comment]
Please post the actual method call and the url formatted link. Just looking at it you have a double apostrophe in a few places (e.g. `Caregiver''s`)

**Comment by asimbashir** [comment]
I have tried on multiple devices and it is working fine on them except one. Below are the details

On Samsung S8, it gives 403 error which is correct because I'm not passing header token for now. Kindly see the stack trace 
- Device OS version: `7.0`
- Device Manufacturer: `Samsung`
- Device Name: `Samsung Galaxy S8`
`E/ExoPlayerImplInternal: Internal track renderer error.
                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:154)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                          Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                             at java.lang.Thread.run(Thread.java:762)`

On Samsung Galaxy Tab 4, it gives 400 bad request error. I tried native VideoView on this device and it gives the same 400 bad request error even though videos are working fine on other devices if we provide header token. 400 bad request should not be the response in any case.
- Device OS version: `5.1.1`
- Devide Manufacturer: `Samsung`
- Device Name: `Samsung Galaxy Tab 4`

`ExoPlayerImplInternal: Internal track renderer error.
                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
                             at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:145)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                          Caused by: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 400
                             at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:210)
                             at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
                             at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:720)
                             at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                             at java.lang.Thread.run(Thread.java:818)`

**Comment by brianwernick** [comment]
Have you tried using the OKHttp client instead of the default client? 
see the Demo [`App#configureExoMedia()`](https://github.com/brianwernick/ExoMedia/blob/master/demo/src/main/java/com/devbrackets/android/exomediademo/App.java#L70) for an example

**Comment by asimbashir** [comment]
OkHttpClient worked like a charm.

Thanks mate!

**Comment by asimbashir** [comment]
By the way any idea why native http client is crashing on a particular device and working fine on others?

**Comment by brianwernick** [comment]
I can't say for sure, but my assumption is that Samsung has modified the http client on that device that has caused a bug.
