### ISSUE TITLE
Streaming works in Android 5, but not Android 4.x

### ISSUE THREAD

**Issue by ahpiau18** [brianwernick/ExoMedia#57]
player = new EMAudioPlayer(this);
String path = "http://hitzfm2.serverhostingcenter.com:8920/;";
Uri uri = Uri.parse(path);
player.setAudioStreamType(AudioManager.STREAM_MUSIC);
player.setDataSource(getContext(), uri, MediaUtil.MediaType.MP3);
player.prepareAsync();
player.start();

I can stream the audio in Android 5.0, but not in Android 4.
i got the error as below.

 Internal track renderer error.                                                                                                     com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://hitzfm2.serverhostingcenter.com:8920/;
                                                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:154)
                                                                                                         at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:145)
                                                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
                                                                                                         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
                                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                                                      Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://hitzfm2.serverhostingcenter.com:8920/;
                                                                                                         at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
                                                                                                         at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136)
                                                                                                         at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733)
                                                                                                         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
                                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                         at java.lang.Thread.run(Thread.java:841)
                                                                                                      Caused by: java.net.ProtocolException: Unexpected status line: ICY 200 OK
                                                                                                         at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
                                                                                                         at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                                                                         at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                                                                         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                                                                         at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                                                         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                                                         at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                                                         at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
                                                                                                         at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:191)
                                                                                                         at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:136) 
                                                                                                         at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:733) 
                                                                                                         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
                                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                                         at java.lang.Thread.run(Thread.java:841)

**Comment by se-bastiaan** [comment]
This is an ExoPlayer issue, not in ExoMedia.

**Comment by se-bastiaan** [comment]
Once the next version of ExoMedia is released you can fix this by providing your own custom RenderBuilder using https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L760.

You can just extend the default `RenderBuilder` and use https://github.com/google/ExoPlayer/blob/master/extensions/okhttp/src/main/java/com/google/android/exoplayer/ext/okhttp/OkHttpDataSource.java instead of the `DefaultUriDataSource`

**Comment by brianwernick** [comment]
Yeah, I'm going to close it since it is not anything we (ExoMedia) are doing.
