### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/ExoPlayer$ExoPlayerComponent;ILjava/lang/Object;)V in class

### ISSUE THREAD

**Issue by ntpanchal** [brianwernick/ExoMedia#600]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `5.0`, `5.1`, `6.0` and `8.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Samsung`, `MI A1`, `Moto G2`
 
###### Reproduction Steps
 0. Implement all the steps from this library step by step.
 1. When click on video list which is open from sample list.
 2. It will give following trace.

###### Expected Result
- Video will Play
###### Actual Result
**Trace**

Process: com.example.exomediademo, PID: 12066
    java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/ExoPlayer$ExoPlayerComponent;ILjava/lang/Object;)V in class Lcom/google/android/exoplayer2/ExoPlayer$ExoPlayerMessage; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayer$ExoPlayerMessage' appears in /data/app/com.example.exomediademo-SmqOMz5SgFXY9o-Ss34hpg==/split_lib_dependencies_apk.apk)
        at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.sendMessage(ExoMediaPlayer.java:496)
        at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.setSurface(ExoMediaPlayer.java:232)
        at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.onSurfaceReady(ExoVideoDelegate.java:197)
        at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView$HolderCallback.surfaceCreated(ExoSurfaceVideoView.java:185)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:664)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2337)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by brianwernick** [comment]
See #584
