### ISSUE TITLE
Unable to set UserAgent in ExoMedia

### ISSUE THREAD

**Issue by meet2011** [brianwernick/ExoMedia#602]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Xiaomi`
 - Device Name: `A1`
 
I have configured `DataSourceFactory` inside Application class but when I try to play video app crashes with no class found error.

**build.gradle**

   ```
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'

    implementation 'com.github.bumptech.glide:glide:4.3.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'

    implementation 'com.devbrackets.android:exomedia:4.1.0'
    implementation 'com.google.android.exoplayer:extension-okhttp:2.7.3'

```

```
private void configureExoMedia() {

        // Registers the media sources to use the OkHttp client instead of the standard Apache one
        // Note: the OkHttpDataSourceFactory can be found in the ExoPlayer extension library `extension-okhttp`

        ExoMedia.setDataSourceFactoryProvider(new ExoMedia.DataSourceFactoryProvider() {
            @NonNull
            @Override
            public DataSource.Factory provide(@NonNull String userAgent, @Nullable TransferListener<? super DataSource> listener) {
                // Updates the network data source to use the OKHttp implementation
                DataSource.Factory upstreamFactory = new OkHttpDataSourceFactory(new OkHttpClient(), "demo897", listener);

                // Adds a cache around the upstreamFactory
                Cache cache = new SimpleCache(getCacheDir(), new LeastRecentlyUsedCacheEvictor(50 * 1024 * 1024));
                return new CacheDataSourceFactory(cache, upstreamFactory, CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);
            }
        });
    }
```

**Error**

```
FATAL EXCEPTION: main
Process: com.vyomsoftware.tvmak, PID: 7536
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/AdaptiveMediaSourceEventListener$EventDispatcher;
at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:118)
at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:92)
at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:75)
at com.devbrackets.android.exomedia.core.source.builder.HlsMediaSourceBuilder.build(HlsMediaSourceBuilder.java:20) 
at com.devbrackets.android.exomedia.core.source.MediaSourceProvider.generate(MediaSourceProvider.java:44)
at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.setUri(ExoMediaPlayer.java:191)
at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setVideoUri(ExoVideoDelegate.java:72)
at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setVideoUri(ExoVideoDelegate.java:60)
at com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView.setVideoUri(ExoTextureVideoView.java:70)
at com.devbrackets.android.exomedia.ui.widget.VideoView.setVideoURI(VideoView.java:269)
at com.vyomsoftware.tvmak.VideoViewActivity.setupVideoView(VideoViewActivity.java:59)
at com.vyomsoftware.tvmak.VideoViewActivity.onCreate(VideoViewActivity.java:43)
at android.app.Activity.performCreate(Activity.java:6975)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:172)
at android.app.ActivityThread.main(ActivityThread.java:6637)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.source.AdaptiveMediaSourceEventListener$EventDispatcher" on path: DexPathList[[zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/base.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_resources_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.vyomsoftware.tvmak-QwJ61A7cVs_Ep0PKVLHGOw==/lib/arm64, /system/lib64, /system/vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:118) 
at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:92) 
at com.google.android.exoplayer2.source.hls.HlsMediaSource.<init>(HlsMediaSource.java:75) 
at com.devbrackets.android.exomedia.core.source.builder.HlsMediaSourceBuilder.build(HlsMediaSourceBuilder.java:20) 
at com.devbrackets.android.exomedia.core.source.MediaSourceProvider.generate(MediaSourceProvider.java:44) 
at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.setUri(ExoMediaPlayer.java:191) 
at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setVideoUri(ExoVideoDelegate.java:72) 
at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setVideoUri(ExoVideoDelegate.java:60) 
at com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView.setVideoUri(ExoTextureVideoView.java:70) 
at com.devbrackets.android.exomedia.ui.widget.VideoView.setVideoURI(VideoView.java:269) 
at com.vyomsoftware.tvmak.VideoViewActivity.setupVideoView(VideoViewActivity.java:59) 
at com.vyomsoftware.tvmak.VideoViewActivity.onCreate(VideoViewActivity.java:43) 
at android.app.Activity.performCreate(Activity.java:6975) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2784) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906) 
at android.app.ActivityThread.-wrap11(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605) 
at android.os.Handler.dispatchMessage(Handler.java:105) 
at android.os.Looper.loop(Looper.java:172) 
at android.app.ActivityThread.main(ActivityThread.java:6637) 

```

**Comment by brianwernick** [comment]
See #584, Until a new version of ExoMedia is published using the ExoPlayers 2.7 release you'll need to use the `2.6.0` version (i.e. `implementation 'com.google.android.exoplayer:extension-okhttp:2.6.0'`
