### ISSUE TITLE
CalledFromWrongThreadException crash

### ISSUE THREAD

**Issue by sudansh** [brianwernick/ExoMedia#609]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `S7 Edge`
 
###### Reproduction Steps
 0.  On open it crashes. This doesn't happen always, but most of the time.

###### Expected Result
Shouldn't crash.

###### Actual Result
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

at com.devbrackets.android.exomedia.ui.widget.VideoView.a(VideoView.java:455)
com.devbrackets.android.exomedia.ui.widget.VideoView$b.onAudioFocusChange(VideoView.java:925)

**Comment by brianwernick** [comment]
>open it
Open what? the demo app, your app, etc.

**Comment by sudansh** [comment]
sorry. my app.

**Comment by brianwernick** [comment]
Sorry for the late response. 
It sounds like you might be making a UI call from an `AsyncTask` (or other background thread utility). I can't say for certain without seeing the full stacktrace or the source that is actually calling it.

**Comment by brianwernick** [comment]
```
Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7256)
       at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1081)
       at android.view.ViewGroup.invalidateChild(ViewGroup.java:4976)
       at android.view.View.invalidateInternal(View.java:12747)
       at android.view.View.invalidate(View.java:12711)
       at android.view.View.setFlags(View.java:10692)
       at android.view.View.setVisibility(View.java:7165)
       at com.kryptolabs.android.speakerswire.ui.broadcasts.BroadcastZeroFragment.onPlayerStarted(BroadcastZeroFragment.java:1771)
       at com.devbrackets.android.exomedia.core.ListenerMux.onStateChanged(ListenerMux.java:135)
       at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.reportPlayerState(ExoMediaPlayer.java:628)
       at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.onPlayerStateChanged(ExoMediaPlayer.java:166)
       at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:188)
       at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.setPlayWhenReady(ExoMediaPlayer.java:438)
       at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.start(ExoVideoDelegate.java:122)
       at com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView.start(ExoTextureVideoView.java:111)
       at com.devbrackets.android.exomedia.ui.widget.VideoView.start(VideoView.java:426)
       at com.devbrackets.android.exomedia.ui.widget.VideoView$AudioFocusHelper.onAudioFocusChange(VideoView.java:910)
       at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:3128)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at com.kryptolabs.android.speakerswire.ui.broadcasts.agora.openlive.model.ABWorkerThread.run(ABWorkerThread.java:76)
```
Looks like you are running functionality on a non-UI thread `ABWorkerThread`
