### ISSUE TITLE
How to set user agent ? 

### ISSUE THREAD

**Issue by khazra18** [brianwernick/ExoMedia#649]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.2`
 - Device OS version: `6.0`
 - Devide Manufacturer: `ASUS`
 - Device Name: `Zenfone`
 
###### Reproduction Steps
  How can i set useragent manually  ? please help !!!

I have used 

```
ExoMedia.setDataSourceFactoryProvider(new ExoMedia.DataSourceFactoryProvider() {
            @NonNull
            @Override
            public DataSource.Factory provide(@NonNull String userAgent, @Nullable TransferListener<? super DataSource> listener) {
                // Updates the network data source to use the OKHttp implementation
                DataSource.Factory upstreamFactory = new OkHttpDataSourceFactory(new OkHttpClient(), "Useragent", listener);

                // Adds a cache around the upstreamFactory
                Cache cache = new SimpleCache(getCacheDir(), new LeastRecentlyUsedCacheEvictor(50 * 1024 * 1024));
                return new CacheDataSourceFactory(cache, upstreamFactory, CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR);
            }
        });
```

Getting this error 

------------------------------------------------------------

```
09-14 13:11:12.282 8153-8153/com.iptvdna.stplayer E/ExoMediaPlayer: Unable to seek across windows, falling back to in-window seeking
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.iptvdna.stplayer/cache
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:124)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:111)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:83)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.iptvdna.stplayer.Activity.LiveScreenNew$1.provide(LiveScreenNew.java:118)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.source.builder.MediaSourceBuilder.buildDataSourceFactory(MediaSourceBuilder.java:40)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.source.builder.DefaultMediaSourceBuilder.build(DefaultMediaSourceBuilder.java:35)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.source.MediaSourceProvider.generate(MediaSourceProvider.java:54)
09-14 13:11:12.284 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.setUri(ExoMediaPlayer.java:191)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setVideoUri(ExoVideoDelegate.java:73)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setVideoUri(ExoVideoDelegate.java:61)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.core.video.exo.ExoTextureVideoView.setVideoUri(ExoTextureVideoView.java:73)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.devbrackets.android.exomedia.ui.widget.VideoView.setVideoURI(VideoView.java:295)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.iptvdna.stplayer.Activity.LiveScreenNew.playEmvideoView(LiveScreenNew.java:344)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.iptvdna.stplayer.Activity.LiveScreenNew.SuccessResponse(LiveScreenNew.java:481)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.iptvdna.stplayer.NetworkOperation.JSONRequestResponse$1.onResponse(JSONRequestResponse.java:83)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.iptvdna.stplayer.NetworkOperation.JSONRequestResponse$1.onResponse(JSONRequestResponse.java:77)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5451)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-14 13:11:12.285 8153-8153/com.iptvdna.stplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by brianwernick** [comment]
The error you are seeing it pretty explicit (`java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.iptvdna.stplayer/cache`). You need to close the prior `SimpleCache` before using the same folder again, or in this case I would recommend creating a shared instance of the `SimpleCache`.
