### ISSUE TITLE
Hi bro, When I click Home btn, then I back my app,the video can't play and I get some error

### ISSUE THREAD

**Issue by 15201511635** [brianwernick/ExoMedia#655]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
1.  Click home, in background
2.return my app，I call mVideoView.start() and seekTo(position) 
3.I get  some error message:
java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
                                                                                at com.google.android.gles_jni.EGLImpl._eglCreateWindowSurface(Native Method)
                                                                                at com.google.android.gles_jni.EGLImpl.eglCreateWindowSurface(EGLImpl.java:92)
                                                                                at com.devbrackets.android.exomedia.core.video.ResizingSurfaceView.clearSurface(ResizingSurfaceView.java:234)
                                                                                at com.devbrackets.android.exomedia.core.ListenerMux.onStateChanged(ListenerMux.java:151)
                                                                                at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.reportPlayerState(ExoMediaPlayer.java:808)
                                                                                at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.onPlayerStateChanged(ExoMediaPlayer.java:180)
                                                                                at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:198)
                                                                                at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.setPlayWhenReady(ExoMediaPlayer.java:443)
                                                                                at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.start(ExoVideoDelegate.java:123)
                                                                                at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.start(ExoSurfaceVideoView.java:112)
                                                                                at com.devbrackets.android.exomedia.ui.widget.VideoView.start(VideoView.java:424)

###### Expected Result
I want when I return my app, I can play my video continue, and seek to a position, I hope you can solve it, tanks .Good luck for you

**Comment by brianwernick** [comment]
I don't have enough information to reproduce this. Are you calling `start()` and `seekTo()` in `onStart`, `onResume`, etc. How long is the app in the background, are you doing any other functionality that will impact the Video playback? Are you using a service?
