### ISSUE TITLE
UnrecognizedInputFormatException: None of the available extractors

### ISSUE THREAD

**Issue by vanhung1710** [brianwernick/ExoMedia#656]
I play this link: http://ott.realplaytv.net:12388/?header=hplus&name=Vinh_Long_1&cdn=1
It works well on VLC but I meet this exception when I use your library

UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:931)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by brianwernick** [comment]
That URL doesn't contain the information needed to determine the media type so ExoMedia falls back to the default extractor which handles standard formats (e.g. `mp4`). You'll need to specify the `MediaSource` yourself or update the url to include the media format as an extension (e.g. `baseUrl/file.m3u8`)
