### ISSUE TITLE
Binary XML file: Error inflating class com.devbrackets.android.exomedia.EMVideoView

### ISSUE THREAD

**Issue by ivanovpv** [brianwernick/ExoMedia#68]
Here's my layout xml file:

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            >
            <TextView
                android:id="@+id/fieldName"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="@dimen/default_text_size"
                />
            <com.devbrackets.android.exomedia.EMVideoView
                android:id="@+id/fieldValue"
                android:layout_width="match_parent"
                android:layout_height="300dp"
                android:layout_gravity="center"
                android:layout_below="@id/fieldName"
                android:layout_alignParentLeft="true"
                android:layout_alignParentRight="true"
                app:defaultControlsEnabled="true"
                />
        </RelativeLayout>

When I'm inflating it dymamically:

        view=LayoutInflater.from(parent.getContext()).inflate(R.layout.field_video_layout, parent, false);

 using Gradled jar linked through 

       compile 'com.devbrackets.android:exomedia:2.5.1'

it works perfect, but whenever I embed ExoMedia sources as library to my project, like:

      compile project(":exomedia")

where **:exomedia** is library subproject I have this:

         android.view.InflateException: Binary XML file line #44: Error inflating class  com.devbrackets.android.exomedia.EMVideoView
                                           at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                           at ru.ivanovpv.cellboxkeeper.android.FieldListAdapter.onCreateViewHolder(FieldListAdapter.java:117)
                                           at ru.ivanovpv.cellboxkeeper.android.FieldListAdapter.onCreateViewHolder(FieldListAdapter.java:75)
                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                           at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                           at android.view.View.layout(View.java:14817)
                                           at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)

No any other changes in sources. What it could be?

**Comment by brianwernick** [comment]
Where in your `build.gradle` do you have the `compile project(':exomedia')` line?  
Does it follow the same ordering in the ExoMedia demos `build.gradle`?

Also, are you including the entire ExoMedia project, or just the `library` project?

**Comment by ivanovpv** [comment]
1) `compile project(':exomedia')` is last line my `build.gradle`

2) I'm using only `library` project

**Comment by ivanovpv** [comment]
Will try recommended ordering

**Comment by ivanovpv** [comment]
Result is the same. Changed `compile project(':exomedia')` ordering and in `settings.gradle` also put as: `include ':exomedia', ':app'`

**Comment by brianwernick** [comment]
Is there any other Log output?  Other than the title, it doesn't point to any EMVideoView source lines...

**Comment by ivanovpv** [comment]
No any other log output. It points to class `com.devbrackets.android.exomedia.EMVideoView`

    android.view.InflateException: Binary XML file line #44: Error inflating class  com.devbrackets.android.exomedia.EMVideoView

**Comment by brianwernick** [comment]
Sorry, I should have been more clear what I meant.  The line 44 points to either an `<ImageView` (API 15 - ) or `android:background="@android:color/black"` neither of which is specific to ExoMedia.

**Comment by brianwernick** [comment]
The other time that you may get that message is if the `<com.devbrackets.android.exomedia.EMVideoView` is the line 44 in your layout, which would mean that ExoMedia hasn't been included (or built) correctly in your project.

**Comment by ivanovpv** [comment]
I have changed android plugin version to `com.android.tools.build:gradle:1.5.0` and it started to work. Issue should be closed

Cheers!

**Comment by brianwernick** [comment]
Well that's good to know. Thanks

**Comment by masmil1988** [comment]
What if I need to use the version 2.2.1 of gradle?
