### ISSUE TITLE
video stream not playing on Android 9 devices 

### ISSUE THREAD

**Issue by bojanxxx** [brianwernick/ExoMedia#691]
video stream not playing on Android 9 devices ( tested on samsung s8, s8+ and s9) when targetSdkversion 28, with targetSdkversion 27 works normaly.

###### Include the following:
 - ExoMedia version: `4.3.0`
 - Device OS version: `9.0`
 - Devide Manufacturer: `samsun`
 - Device Name: `s8+

**Comment by brianwernick** [comment]
Please post any relevant stack trace.
Is this any particular stream (url) or any that you've tried?

**Comment by bojanxxx** [comment]
link for testing   http://m-iptv.net:6204/live/OoesIRzgNP/8kW83aN4dr/46.m3u8 
this problem shows only on android 9 devices  when  targetSdkVersion 28, if i set targetSdkVersion 27 everything is working

error:
 E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://m-iptv.net:6204/live/OoesIRzgNP/8kW83aN4dr/46.m3u8 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:145)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Cleartext HTTP traffic to m-iptv.net not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:467)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:145) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-04-01 17:03:33.728 17289-17289/? E/LLog: For input string: "4C7"
2019-04-01 17:03:33.729 17289-17289/? E/LLog: For input string: "4C7"

**Comment by tupacal** [comment]
> link for testing http://m-iptv.net:6204/live/OoesIRzgNP/8kW83aN4dr/46.m3u8
> this problem shows only on android 9 devices when targetSdkVersion 28, if i set targetSdkVersion 27 everything is working
> 
> error:
> E/ExoPlayerImplInternal: Source error.
> com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://m-iptv.net:6204/live/OoesIRzgNP/8kW83aN4dr/46.m3u8
> at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
> at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
> at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
> at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
> at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:145)
> at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:764)
> Caused by: java.io.IOException: Cleartext HTTP traffic to m-iptv.net not permitted
> at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
> at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:467)
> at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
> at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
> at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
> at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
> at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
> at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
> at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
> at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:145) 
> at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317) 
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
> at java.lang.Thread.run(Thread.java:764) 
> 2019-04-01 17:03:33.728 17289-17289/? E/LLog: For input string: "4C7"
> 2019-04-01 17:03:33.729 17289-17289/? E/LLog: For input string: "4C7"

Try tu use HTTPS. :)

**Comment by RowlandOti** [comment]
@bojanxxx this is not a library issue. Please fix this using this link: https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

**Comment by brianwernick** [comment]
Thanks @RowlandOti
