### ISSUE TITLE
Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView

### ISSUE THREAD

**Issue by waseefakhtar** [brianwernick/ExoMedia#717]
I've found plenty of these issues reported but I can't seem to find the solution that worked for me. Any idea why that might be?

###### Include the following:
 - ExoMedia version: `4.3.0`
 - Device OS version: `10.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy A10`
 
###### Reproduction Steps
 1. Add Exomedia dependency as:

```
implementation ("com.devbrackets.android:exomedia:4.3.0") {
        transitive = true
    }
```

2. Removing ExoPlayer dependency.  

###### Expected Result
Should play the video file.

###### Actual Result
The app crashes upon running the fragment:

```
android.view.InflateException: Binary XML file line #11 in com.test.android:layout/fragment_test_video: Binary XML file line #11 in com.test.android.dev:layout/fragment_test_video: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
    Caused by: android.view.InflateException: Binary XML file line #11 in com.test.android:layout/fragment_test_video: Error inflating class com.devbrackets.android.exomedia.ui.widget.VideoView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.test.android.fragment.BaseFragment.onCreateView(FileRendererFragment.java:66)
        at com.test.android.fragment.TestVideoFragment.onCreateView(TestVideoFragment.java:101)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:26415)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1010)
        at android.view.View.measure(View.java:26415)
2020-07-14 21:03:11.465 7090-7090/com.test.android E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3609)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2352)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2644)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9003)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
        at android.view.Choreographer.doCallbacks(Choreographer.java:794)
        at android.view.Choreographer.doFrame(Choreographer.java:729)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: android.view.InflateException: Binary XML file line #2 in com.test.android:layout/exomedia_default_exo_surface_video_view: Binary XML file line #2 in com.test.android:layout/exomedia_default_exo_surface_video_view: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView
     Caused by: android.view.InflateException: Binary XML file line #2 in com.test.android:layout/exomedia_default_exo_surface_video_view: Error inflating class com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.ViewStub.inflateViewNoAdd(ViewStub.java:272)
        at android.view.ViewStub.inflate(ViewStub.java:305)
        at com.devbrackets.android.exomedia.ui.widget.VideoView.inflateVideoView(VideoView.java:928)
        at com.devbrackets.android.exomedia.ui.widget.VideoView.initView(VideoView.java:885)
        at com.devbrackets.android.exomedia.ui.widget.VideoView.setup(VideoView.java:872)
        at com.devbrackets.android.exomedia.ui.widget.VideoView.<init>(VideoView.java:114)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.test.android.fragment.BaseFragment.onCreateView(FileRendererFragment.java:66)
        at com.test.android.fragment.TestFragment.onCreateView(ExoPlayerRendererFragment.java:101)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
2020-07-14 21:03:11.467 7090-7090/com.test.android E/AndroidRuntime:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:235)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:26415)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1676)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1010)
        at android.view.View.measure(View.java:26415)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3609)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2352)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2644)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2204)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9003)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
        at android.view.Choreographer.doCallbacks(Choreographer.java:794)
        at android.view.Choreographer.doFrame(Choreographer.java:729)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.NoSuchMethodError: No static method newInstance([Lcom/google/android/exoplayer2/Renderer;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;)Lcom/google/android/exoplayer2/ExoPlayer; in class Lcom/google/android/exoplayer2/ExoPlayerFactory; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayerFactory' appears in /data/app/com.test.android-GbUOmdVGlpXA==/base.apk)
        at com.devbrackets.android.exomedia.core.exoplayer.ExoMediaPlayer.<init>(ExoMediaPlayer.java:172)
        at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.initExoPlayer(ExoVideoDelegate.java:271)
        at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.setup(ExoVideoDelegate.java:267)
        at com.devbrackets.android.exomedia.core.video.exo.ExoVideoDelegate.<init>(ExoVideoDelegate.java:58)
2020-07-14 21:03:11.467 7090-7090/com.test.android E/AndroidRuntime:     at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.setup(ExoSurfaceVideoView.java:233)
        at com.devbrackets.android.exomedia.core.video.exo.ExoSurfaceVideoView.<init>(ExoSurfaceVideoView.java:58)
```

**Comment by LnLooFa** [comment]
这个问题怎么解决

**Comment by renxiaohui** [comment]
项目已有的exoplayer版本比exomedia引用的版本高，exoplayer新版本api有变动

**Comment by dariopellegrini** [comment]
Same here

**Comment by codaman** [comment]
i have same problem

**Comment by brianwernick** [comment]
As @renxiaohui stated, please make sure that you aren't explicitly including a different version of the `exoplayer` dependency from what is included by `exomedia`.
