### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE

### ISSUE THREAD

**Issue by sudiptochatterjee-globussoft** [brianwernick/ExoMedia#745]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `43.0`
 - Device OS version: `11.0`
 - Devide Manufacturer: `realme`
 - Device Name: `Realme 8s 5g`
 
 java.lang.RuntimeException: Unable to create application com.jeff.hitsradio.App: java.lang.IllegalArgumentException: com.jeff.hitsradio: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

 Caused by: java.lang.IllegalArgumentException: com.jeff.hitsradio: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:730)
        at android.app.PendingIntent.getService(PendingIntent.java:692)
        at com.devbrackets.android.playlistcore.manager.BasePlaylistManager.createPendingIntent(BasePlaylistManager.kt:493)
        at com.devbrackets.android.playlistcore.manager.BasePlaylistManager.constructControlIntents(BasePlaylistManager.kt:469)
        at com.devbrackets.android.playlistcore.manager.BasePlaylistManager.<init>(BasePlaylistManager.kt:143)
        at com.devbrackets.android.playlistcore.manager.ListPlaylistManager.<init>(ListPlaylistManager.kt:30)
        at com.jeff.hitsradio.manager.PlaylistManager.<init>(PlaylistManager.java:21)
        at com.jeff.hitsradio.App.onCreate(App.java:27)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1225)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7077)

**Comment by sikhworldapp** [comment]
I have fixed the issue by importing **playlist core** library as module in android studio  and then add flagMutable where required.

**Comment by brianwernick** [comment]
See #742
