### ISSUE TITLE
Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by isabsent** [brianwernick/ExoMedia#770]
First start on Android 7.0 device leads to:

    2022-09-04 13:37:40.993 16702-16817/com.devbrackets.android.exomediademo E/AndroidRuntime: FATAL EXCEPTION: bufferRepeater
    Process: com.devbrackets.android.exomediademo, PID: 16702
    java.lang.IllegalStateException: Player is accessed on the wrong thread.
    Current thread: 'bufferRepeater'
    Expected thread: 'main'
    See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
        at androidx.media3.exoplayer.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2608)
        at androidx.media3.exoplayer.ExoPlayerImpl.getBufferedPosition(ExoPlayerImpl.java:1046)
        at androidx.media3.common.BasePlayer.getBufferedPercentage(BasePlayer.java:355)
        at com.devbrackets.android.exomedia.nmp.ExoMediaPlayerImpl.getBufferedPercent(ExoMediaPlayerImpl.kt:116)
        at com.devbrackets.android.exomedia.nmp.ExoMediaPlayerImpl$bufferTimer$2$invoke$$inlined$fixedRateTimer$1.run(Timer.kt:149)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

on screen rotations with simultaneous back button pressing. [Dump files](https://github.com/brianwernick/ExoMedia/files/9484507/hprof.zip).

**Comment by brianwernick** [comment]
Thank you for reporting this issue; this is planned to be fixed before we release 5.0
